// IDs del 601 al 700
export const QUESTION_DEPORTE = [
  {
    id: 601,
    question: "¿Cuántos jugadores tiene un equipo de fútbol en el campo?",
    options: ["9", "10", "11", "12"],
    correctAnswerIndex: 2,
  },
  {
    id: 602,
    question: "¿Cada cuántos años se celebra el Mundial de fútbol?",
    options: ["2", "3", "4", "5"],
    correctAnswerIndex: 2,
  },
  {
    id: 603,
    question: "¿Qué país ha ganado más Copas del Mundo de fútbol?",
    options: ["Alemania", "Italia", "Argentina", "Brasil"],
    correctAnswerIndex: 3,
  },
  {
    id: 604,
    question: "¿Cuántos puntos vale un triple en baloncesto?",
    options: ["1", "2", "3", "4"],
    correctAnswerIndex: 2,
  },
  {
    id: 605,
    question: "¿En qué deporte se usa un bate?",
    options: ["Tenis", "Béisbol", "Golf", "Hockey"],
    correctAnswerIndex: 1,
  },
  {
    id: 606,
    question: "¿Cuál es la duración de un partido de fútbol profesional?",
    options: ["80 minutos", "90 minutos", "100 minutos", "120 minutos"],
    correctAnswerIndex: 1,
  },
  {
    id: 607,
    question: "¿Qué deporte practica Lionel Messi?",
    options: ["Baloncesto", "Tenis", "Fútbol", "Rugby"],
    correctAnswerIndex: 2,
  },
  {
    id: 608,
    question: "¿Cuántos sets se juegan en un partido de tenis masculino de Grand Slam?",
    options: ["3", "4", "5", "6"],
    correctAnswerIndex: 2,
  },
  {
    id: 609,
    question: "¿Qué país es famoso por el sumo?",
    options: ["China", "Corea", "Japón", "Tailandia"],
    correctAnswerIndex: 2,
  },
  {
    id: 610,
    question: "¿Qué deporte se juega en Wimbledon?",
    options: ["Golf", "Tenis", "Críquet", "Rugby"],
    correctAnswerIndex: 1,
  },

  {
    id: 611,
    question: "¿Cuántos jugadores hay en un equipo de baloncesto en cancha?",
    options: ["4", "5", "6", "7"],
    correctAnswerIndex: 1,
  },
  {
    id: 612,
    question: "¿Qué país originó los Juegos Olímpicos?",
    options: ["Italia", "Grecia", "Egipto", "Francia"],
    correctAnswerIndex: 1,
  },
  {
    id: 613,
    question: "¿En qué deporte se usa la palabra 'knockout'?",
    options: ["Lucha libre", "Boxeo", "Karate", "Judo"],
    correctAnswerIndex: 1,
  },
  {
    id: 614,
    question: "¿Cuántos anillos tiene el símbolo olímpico?",
    options: ["4", "5", "6", "7"],
    correctAnswerIndex: 1,
  },
  {
    id: 615,
    question: "¿Qué deporte practica Michael Jordan?",
    options: ["Béisbol", "Baloncesto", "Fútbol americano", "Hockey"],
    correctAnswerIndex: 1,
  },
  {
    id: 616,
    question: "¿Cuántos hoyos tiene un campo de golf estándar?",
    options: ["9", "12", "18", "24"],
    correctAnswerIndex: 2,
  },
  {
    id: 617,
    question: "¿Qué deporte utiliza una red y un volante?",
    options: ["Tenis", "Bádminton", "Vóley", "Ping-pong"],
    correctAnswerIndex: 1,
  },
  {
    id: 618,
    question: "¿Cuál es el evento deportivo más visto del mundo?",
    options: ["Super Bowl", "Juegos Olímpicos", "Mundial de fútbol", "Tour de Francia"],
    correctAnswerIndex: 2,
  },
  {
    id: 619,
    question: "¿En qué deporte se usa un casco y hombreras?",
    options: ["Rugby", "Fútbol americano", "Hockey", "Lacrosse"],
    correctAnswerIndex: 1,
  },
  {
    id: 620,
    question: "¿Cuántos puntos vale un touchdown?",
    options: ["3", "6", "7", "10"],
    correctAnswerIndex: 1,
  },

  {
    id: 621,
    question: "¿Qué deporte se juega en el Tour de Francia?",
    options: ["Motociclismo", "Ciclismo", "Automovilismo", "Atletismo"],
    correctAnswerIndex: 1,
  },
  {
    id: 622,
    question: "¿Cuál es el máximo organismo del fútbol mundial?",
    options: ["UEFA", "CONMEBOL", "FIFA", "IOC"],
    correctAnswerIndex: 2,
  },
  {
    id: 623,
    question: "¿Qué deporte combina natación, ciclismo y carrera?",
    options: ["Pentatlón", "Triatlón", "Decatlón", "Ironman"],
    correctAnswerIndex: 1,
  },
  {
    id: 624,
    question: "¿Cuántos jugadores tiene un equipo de voleibol en cancha?",
    options: ["5", "6", "7", "8"],
    correctAnswerIndex: 1,
  },
  {
    id: 625,
    question: "¿Qué país ganó el Mundial de fútbol 2022?",
    options: ["Francia", "Brasil", "Argentina", "Croacia"],
    correctAnswerIndex: 2,
  },
  {
    id: 626,
    question: "¿En qué deporte se usa un puck?",
    options: ["Hockey sobre hielo", "Lacrosse", "Rugby", "Críquet"],
    correctAnswerIndex: 0,
  },
  {
    id: 627,
    question: "¿Qué deporte se practica en el ring?",
    options: ["Judo", "Boxeo", "Karate", "Taekwondo"],
    correctAnswerIndex: 1,
  },
  {
    id: 628,
    question: "¿Cuántas medallas de oro puede ganar un atleta en una prueba?",
    options: ["1", "2", "3", "Ilimitadas"],
    correctAnswerIndex: 0,
  },
  {
    id: 629,
    question: "¿Qué deporte tiene posiciones como base y escolta?",
    options: ["Fútbol", "Baloncesto", "Hockey", "Rugby"],
    correctAnswerIndex: 1,
  },
  {
    id: 630,
    question: "¿Qué país es famoso por el cricket?",
    options: ["Estados Unidos", "India", "España", "Italia"],
    correctAnswerIndex: 1,
  },

  {
    id: 631,
    question: "¿Cuántos jugadores tiene un equipo de rugby?",
    options: ["11", "13", "15", "18"],
    correctAnswerIndex: 2,
  },
  {
    id: 632,
    question: "¿Qué deporte practica Usain Bolt?",
    options: ["Ciclismo", "Atletismo", "Fútbol", "Natación"],
    correctAnswerIndex: 1,
  },
  {
    id: 633,
    question: "¿En qué deporte se usa una raqueta?",
    options: ["Béisbol", "Tenis", "Golf", "Críquet"],
    correctAnswerIndex: 1,
  },
  {
    id: 634,
    question: "¿Cuántos tiempos tiene un partido de fútbol?",
    options: ["1", "2", "3", "4"],
    correctAnswerIndex: 1,
  },
  {
    id: 635,
    question: "¿Qué deporte se juega en el Super Bowl?",
    options: ["Béisbol", "Baloncesto", "Fútbol americano", "Rugby"],
    correctAnswerIndex: 2,
  },
  {
    id: 636,
    question: "¿Qué país organiza el torneo Roland Garros?",
    options: ["Italia", "España", "Francia", "Suiza"],
    correctAnswerIndex: 2,
  },
  {
    id: 637,
    question: "¿Cuántos jugadores hay en un equipo de béisbol?",
    options: ["7", "8", "9", "10"],
    correctAnswerIndex: 2,
  },
  {
    id: 638,
    question: "¿Qué deporte usa guantes y casco?",
    options: ["Boxeo", "Béisbol", "Críquet", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 639,
    question: "¿Qué deporte se practica en una pista ovalada?",
    options: ["Atletismo", "Ciclismo", "Patinaje", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 640,
    question: "¿Cuántos sets se juegan en voleibol profesional?",
    options: ["3", "4", "5", "6"],
    correctAnswerIndex: 2,
  },

  {
    id: 641,
    question: "¿Qué país ganó más medallas en los Juegos Olímpicos?",
    options: ["China", "Rusia", "Estados Unidos", "Alemania"],
    correctAnswerIndex: 2,
  },
  {
    id: 642,
    question: "¿Qué deporte usa una tabla y olas?",
    options: ["Surf", "Vela", "Kayak", "Remo"],
    correctAnswerIndex: 0,
  },
  {
    id: 643,
    question: "¿Qué deporte practica Rafael Nadal?",
    options: ["Tenis", "Pádel", "Bádminton", "Squash"],
    correctAnswerIndex: 0,
  },
  {
    id: 644,
    question: "¿En qué deporte se usa un aro?",
    options: ["Baloncesto", "Gimnasia rítmica", "Atletismo", "Natación"],
    correctAnswerIndex: 1,
  },
  {
    id: 645,
    question: "¿Cuántos árbitros hay en un partido de fútbol?",
    options: ["1", "2", "3", "4"],
    correctAnswerIndex: 2,
  },
  {
    id: 646,
    question: "¿Qué deporte se juega en el Madison Square Garden?",
    options: ["Hockey", "Baloncesto", "Boxeo", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 647,
    question: "¿Qué país es famoso por el rugby?",
    options: ["Brasil", "Nueva Zelanda", "España", "México"],
    correctAnswerIndex: 1,
  },
  {
    id: 648,
    question: "¿Cuántos puntos vale un penal en fútbol?",
    options: ["1", "2", "3", "Depende"],
    correctAnswerIndex: 0,
  },
  {
    id: 649,
    question: "¿Qué deporte utiliza un cronómetro?",
    options: ["Atletismo", "Natación", "Ciclismo", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 650,
    question: "¿Qué país ganó el Mundial femenino 2019?",
    options: ["Alemania", "Estados Unidos", "Francia", "Inglaterra"],
    correctAnswerIndex: 1,
  },

  {
    id: 651,
    question: "¿Qué deporte se juega con un balón ovalado?",
    options: ["Fútbol", "Rugby", "Baloncesto", "Vóley"],
    correctAnswerIndex: 1,
  },
  {
    id: 652,
    question: "¿Qué deporte se practica en piscina?",
    options: ["Natación", "Waterpolo", "Saltos", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 653,
    question: "¿Cuántos jugadores hay en un equipo de waterpolo?",
    options: ["6", "7", "8", "9"],
    correctAnswerIndex: 1,
  },
  {
    id: 654,
    question: "¿Qué deporte tiene categorías de peso?",
    options: ["Boxeo", "Judo", "Halterofilia", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 655,
    question: "¿Qué país es sede del Superclásico Boca vs River?",
    options: ["Brasil", "Uruguay", "Argentina", "Chile"],
    correctAnswerIndex: 2,
  },
  {
    id: 656,
    question: "¿Qué deporte usa un trampolín?",
    options: ["Gimnasia", "Natación", "Clavados", "Parkour"],
    correctAnswerIndex: 0,
  },
  {
    id: 657,
    question: "¿Cuántos jugadores tiene un equipo de hockey sobre hielo?",
    options: ["5", "6", "7", "8"],
    correctAnswerIndex: 1,
  },
  {
    id: 658,
    question: "¿Qué deporte se practica en los X Games?",
    options: ["Surf", "Skate", "Snowboard", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 659,
    question: "¿Qué país ganó el Mundial 2014?",
    options: ["Brasil", "Argentina", "Alemania", "España"],
    correctAnswerIndex: 2,
  },
  {
    id: 660,
    question: "¿Qué deporte usa zapatillas con clavos?",
    options: ["Fútbol", "Atletismo", "Rugby", "Golf"],
    correctAnswerIndex: 1,
  },

  {
    id: 661,
    question: "¿Cuántos puntos vale un gol en hockey?",
    options: ["1", "2", "3", "Depende"],
    correctAnswerIndex: 0,
  },
  {
    id: 662,
    question: "¿Qué deporte se practica en un velódromo?",
    options: ["Ciclismo", "Atletismo", "Patinaje", "Motociclismo"],
    correctAnswerIndex: 0,
  },
  {
    id: 663,
    question: "¿Qué país es famoso por el béisbol?",
    options: ["México", "Cuba", "España", "Argentina"],
    correctAnswerIndex: 1,
  },
  {
    id: 664,
    question: "¿Qué deporte tiene una línea de tres puntos?",
    options: ["Baloncesto", "Hockey", "Rugby", "Handball"],
    correctAnswerIndex: 0,
  },
  {
    id: 665,
    question: "¿Qué deporte practica Serena Williams?",
    options: ["Atletismo", "Tenis", "Golf", "Natación"],
    correctAnswerIndex: 1,
  },
  {
    id: 666,
    question: "¿Cuántos jugadores tiene un equipo de handball?",
    options: ["6", "7", "8", "9"],
    correctAnswerIndex: 1,
  },
  {
    id: 667,
    question: "¿Qué deporte se juega con sticks?",
    options: ["Hockey", "Béisbol", "Críquet", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 668,
    question: "¿Qué país ganó el Mundial 2010?",
    options: ["Alemania", "Brasil", "España", "Países Bajos"],
    correctAnswerIndex: 2,
  },
  {
    id: 669,
    question: "¿Qué deporte se practica en arena?",
    options: ["Vóley playa", "Surf", "Fútbol playa", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 670,
    question: "¿Cuántos rounds tiene un combate profesional de boxeo?",
    options: ["10", "12", "14", "15"],
    correctAnswerIndex: 1,
  },

  {
    id: 671,
    question: "¿Qué deporte se practica en el octágono?",
    options: ["Boxeo", "UFC", "Lucha libre", "Karate"],
    correctAnswerIndex: 1,
  },
  {
    id: 672,
    question: "¿Qué deporte usa un mazo?",
    options: ["Golf", "Polo", "Críquet", "Hockey"],
    correctAnswerIndex: 1,
  },
  {
    id: 673,
    question: "¿Qué país es famoso por el atletismo de fondo?",
    options: ["Estados Unidos", "Kenia", "China", "Alemania"],
    correctAnswerIndex: 1,
  },
  {
    id: 674,
    question: "¿Qué deporte se juega en el Abierto de Australia?",
    options: ["Golf", "Tenis", "Críquet", "Rugby"],
    correctAnswerIndex: 1,
  },
  {
    id: 675,
    question: "¿Qué deporte se practica con espada?",
    options: ["Esgrima", "Kendo", "Karate", "Taekwondo"],
    correctAnswerIndex: 0,
  },
  {
    id: 676,
    question: "¿Cuántos jugadores hay en un equipo de fútbol sala?",
    options: ["4", "5", "6", "7"],
    correctAnswerIndex: 1,
  },
  {
    id: 677,
    question: "¿Qué deporte se practica con canasta?",
    options: ["Baloncesto", "Netball", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 678,
    question: "¿Qué país ganó más Copas América?",
    options: ["Argentina", "Brasil", "Uruguay", "Chile"],
    correctAnswerIndex: 2,
  },
  {
    id: 679,
    question: "¿Qué deporte se juega con guantes grandes?",
    options: ["Boxeo", "Béisbol", "Críquet", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 680,
    question: "¿Qué deporte se practica en pista de hielo?",
    options: ["Patinaje", "Hockey", "Curling", "Todos"],
    correctAnswerIndex: 3,
  },

  {
    id: 681,
    question: "¿Qué país es sede del Maracaná?",
    options: ["Argentina", "Brasil", "Portugal", "México"],
    correctAnswerIndex: 1,
  },
  {
    id: 682,
    question: "¿Qué deporte usa una pelota amarilla?",
    options: ["Tenis", "Pádel", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 683,
    question: "¿Cuántos jugadores hay en un equipo de críquet?",
    options: ["9", "10", "11", "12"],
    correctAnswerIndex: 2,
  },
  {
    id: 684,
    question: "¿Qué deporte se practica en una jaula?",
    options: ["Boxeo", "MMA", "Lucha libre", "Karate"],
    correctAnswerIndex: 1,
  },
  {
    id: 685,
    question: "¿Qué deporte usa una red alta?",
    options: ["Tenis", "Vóley", "Bádminton", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 686,
    question: "¿Qué país ganó el Mundial femenino 2023?",
    options: ["Estados Unidos", "Inglaterra", "España", "Suecia"],
    correctAnswerIndex: 2,
  },
  {
    id: 687,
    question: "¿Qué deporte se practica con kettlebells?",
    options: ["CrossFit", "Halterofilia", "Powerlifting", "Gimnasia"],
    correctAnswerIndex: 0,
  },
  {
    id: 688,
    question: "¿Cuántos jugadores hay en un equipo de béisbol en defensa?",
    options: ["7", "8", "9", "10"],
    correctAnswerIndex: 2,
  },
  {
    id: 689,
    question: "¿Qué deporte se practica en una cancha de 28 metros?",
    options: ["Baloncesto", "Handball", "Vóley", "Fútbol sala"],
    correctAnswerIndex: 0,
  },
  {
    id: 690,
    question: "¿Qué país es famoso por el hockey sobre hielo?",
    options: ["Canadá", "Brasil", "España", "Australia"],
    correctAnswerIndex: 0,
  },

  {
    id: 691,
    question: "¿Qué deporte utiliza una pértiga?",
    options: ["Salto alto", "Salto con pértiga", "Triple salto", "Largo"],
    correctAnswerIndex: 1,
  },
  {
    id: 692,
    question: "¿Qué deporte se practica en aguas abiertas?",
    options: ["Natación", "Vela", "Surf", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 693,
    question: "¿Qué país ganó el Mundial 2006?",
    options: ["Brasil", "Italia", "Alemania", "Francia"],
    correctAnswerIndex: 1,
  },
  {
    id: 694,
    question: "¿Qué deporte usa protecciones en las espinillas?",
    options: ["Rugby", "Hockey", "Fútbol", "Todos"],
    correctAnswerIndex: 2,
  },
  {
    id: 695,
    question: "¿Qué deporte se practica con un disco?",
    options: ["Frisbee", "Hockey", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 696,
    question: "¿Qué país ganó el Mundial 1998?",
    options: ["Brasil", "Francia", "Italia", "Alemania"],
    correctAnswerIndex: 1,
  },
  {
    id: 697,
    question: "¿Qué deporte se juega en cancha de césped?",
    options: ["Hockey", "Rugby", "Fútbol", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 698,
    question: "¿Qué deporte usa cronómetro y juez de llegada?",
    options: ["Atletismo", "Natación", "Ciclismo", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 699,
    question: "¿Qué país es famoso por el surf?",
    options: ["Brasil", "Australia", "Hawái", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 700,
    question: "¿Qué deporte combina fuerza, resistencia y técnica?",
    options: ["CrossFit", "Triatlón", "Gimnasia", "Todos"],
    correctAnswerIndex: 3,
  },
];
