export const QUESTION_ANIMAL = [
  {
    id: 1,
    question: "¿Cuál es el animal más rápido en tierra?",
    options: ["Leopardo", "Guepardo", "León", "Antílope"],
    correctAnswerIndex: 1,
  },
  {
    id: 2,
    question: "¿Qué animal es el más grande que ha existido?",
    options: ["Dinosaurio", "Ballena azul", "Elefante africano", "Megalodón"],
    correctAnswerIndex: 1,
  },
  {
    id: 3,
    question: "¿Qué ave puede volar hacia atrás?",
    options: ["Colibrí", "Águila", "Golondrina", "Pelícano"],
    correctAnswerIndex: 0,
  },
  {
    id: 4,
    question: "¿Cuántos corazones tiene un pulpo?",
    options: ["1", "2", "3", "4"],
    correctAnswerIndex: 2,
  },
  {
    id: 5,
    question: "¿Cuál es el único mamífero que puede volar?",
    options: ["Ardilla voladora", "Murciélago", "Colibrí", "Lémur volador"],
    correctAnswerIndex: 1,
  },
  {
    id: 6,
    question: "¿Qué animal puede regenerar partes de su cuerpo, incluyendo el corazón?",
    options: ["Estrella de mar", "Salamandra", "Ajolote", "Planaria"],
    correctAnswerIndex: 2,
  },
  {
    id: 7,
    question: "¿Qué animal duerme de pie?",
    options: ["Caballo", "Elefante", "Jirafa", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 8,
    question: "¿Cuál es el único animal que no puede saltar?",
    options: ["Elefante", "Tortuga", "Perezoso", "Rinoceronte"],
    correctAnswerIndex: 0,
  },
  {
    id: 9,
    question: "¿Qué animal tiene la lengua más larga en relación a su cuerpo?",
    options: ["Camaleón", "Oso hormiguero", "Murciélago frugívoro", "Picaflor"],
    correctAnswerIndex: 0,
  },
  {
    id: 10,
    question: "¿Qué animal tiene el sueño más largo?",
    options: ["Koala (22 horas)", "Perezoso (20 horas)", "Murciélago pardo (19.9 horas)", "Armadillo (18.5 horas)"],
    correctAnswerIndex: 2,
  },
  {
    id: 11,
    question: "¿Qué animal tiene las huellas dactilares más similares a las humanas?",
    options: ["Chimpancé", "Koala", "Gorila", "Orangután"],
    correctAnswerIndex: 1,
  },
  {
    id: 12,
    question: "¿Cuánto tiempo puede vivir una tortuga gigante de Galápagos?",
    options: ["50-60 años", "80-100 años", "100-150 años", "150-200 años"],
    correctAnswerIndex: 3,
  },
  {
    id: 13,
    question: "¿Qué animal puede girar su cabeza 270 grados?",
    options: ["Lechuza", "Camaleón", "Perezoso", "Suricata"],
    correctAnswerIndex: 0,
  },
  {
    id: 14,
    question: "¿Cuál es el único mamífero venenoso?",
    options: ["Ornitorrinco", "Musaraña", "Solenodonte", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 15,
    question: "¿Qué animal tiene el cerebro más grande en relación a su cuerpo?",
    options: ["Delfín", "Humano", "Chimpancé", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 16,
    question: "¿Cuántos estómagos tiene una vaca?",
    options: ["1", "2", "3", "4"],
    correctAnswerIndex: 3,
  },
  {
    id: 17,
    question: "¿Qué animal puede contener la respiración por más tiempo?",
    options: ["Ballena", "Delfín", "Tortuga marina", "Cachalote"],
    correctAnswerIndex: 3,
  },
  {
    id: 18,
    question: "¿Cuál es el animal nacional de Australia?",
    options: ["Koala", "Canguro", "Emú", "Ornitorrinco"],
    correctAnswerIndex: 1,
  },
  {
    id: 19,
    question: "¿Qué animal tiene la gestación más larga?",
    options: ["Elefante (22 meses)", "Ballena (17 meses)", "Rinoceronte (16 meses)", "Jirafa (15 meses)"],
    correctAnswerIndex: 0,
  },
  {
    id: 20,
    question: "¿Qué animal puede cambiar de sexo durante su vida?",
    options: ["Pez payaso", "Pez loro", "Pez ángel", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 21,
    question: "¿Qué animal tiene la mejor visión?",
    options: ["Águila", "Búho", "Camaleón", "Tiburón martillo"],
    correctAnswerIndex: 0,
  },
  {
    id: 22,
    question: "¿Cuál es el animal más ruidoso del mundo?",
    options: ["Ballena azul", "Monos aulladores", "Cigarra", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 23,
    question: "¿Qué animal tiene los ojos más grandes en relación a su cuerpo?",
    options: ["Tarsero", "Calamar gigante", "Lémur", "Gekko"],
    correctAnswerIndex: 0,
  },
  {
    id: 24,
    question: "¿Cuántas especies de pingüinos existen?",
    options: ["17", "22", "25", "18"],
    correctAnswerIndex: 3,
  },
  {
    id: 25,
    question: "¿Qué animal puede correr más rápido que un caballo en distancias cortas?",
    options: ["Guepardo", "Ostrich", "Leopardo", "Antílope"],
    correctAnswerIndex: 1,
  },
  {
    id: 26,
    question: "¿Cuál es el insecto más fuerte del mundo?",
    options: ["Escarabajo hércules", "Hormiga cortadora", "Escarabajo rinoceronte", "Avispa cazadora"],
    correctAnswerIndex: 0,
  },
  {
    id: 27,
    question: "¿Qué animal tiene el sentido del olfato más desarrollado?",
    options: ["Perro", "Elefante", "Tiburón", "Oso polar"],
    correctAnswerIndex: 3,
  },
  {
    id: 28,
    question: "¿Cuántas horas al día duerme un koala?",
    options: ["18-20", "20-22", "22-24", "16-18"],
    correctAnswerIndex: 1,
  },
  {
    id: 29,
    question: "¿Qué animal puede vivir sin agua por más tiempo?",
    options: ["Camello", "Rata canguro", "Tortuga del desierto", "Escorpión"],
    correctAnswerIndex: 1,
  },
  {
    id: 30,
    question: "¿Cuál es el animal más venenoso del mundo?",
    options: ["Serpiente taipán", "Rana dorada venenosa", "Medusa caja", "Pulpo de anillos azules"],
    correctAnswerIndex: 2,
  },
  {
    id: 31,
    question: "¿Qué animal tiene la piel más resistente?",
    options: ["Cocodrilo", "Rinoceronte", "Hipopótamo", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 32,
    question: "¿Cuánto puede saltar un canguro?",
    options: ["3 metros", "6 metros", "9 metros", "12 metros"],
    correctAnswerIndex: 2,
  },
  {
    id: 33,
    question: "¿Qué animal tiene el periodo de gestación más corto?",
    options: ["Opossum", "Hamster", "Ratón", "Musaraña"],
    correctAnswerIndex: 0,
  },
  {
    id: 34,
    question: "¿Cuál es el animal más alto del mundo?",
    options: ["Elefante", "Jirafa", "Avestruz", "Oso polar"],
    correctAnswerIndex: 1,
  },
  {
    id: 35,
    question: "¿Qué animal tiene la cola más larga en relación a su cuerpo?",
    options: ["Lemur de cola anillada", "Monos araña", "Camaleón", "Gecko"],
    correctAnswerIndex: 1,
  },
  {
    id: 36,
    question: "¿Cuántos dientes tiene un tiburón blanco?",
    options: ["50", "100", "300", "500"],
    correctAnswerIndex: 2,
  },
  {
    id: 37,
    question: "¿Qué animal puede sobrevivir en el espacio exterior?",
    options: ["Tardígrado", "Bacteria extremófila", "Gusano nematodo", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 38,
    question: "¿Cuál es el animal más pequeño del mundo?",
    options: ["Abeja colibrí", "Musaraña etrusca", "Rana Paedophryne amauensis", "Todos son correctos"],
    correctAnswerIndex: 3,
  },
  {
    id: 39,
    question: "¿Qué porcentaje de su vida pasa un perezoso durmiendo?",
    options: ["50%", "75%", "85%", "90%"],
    correctAnswerIndex: 2,
  },
  {
    id: 40,
    question: "¿Cuántas especies de mariposas existen aproximadamente?",
    options: ["10,000", "20,000", "30,000", "40,000"],
    correctAnswerIndex: 1,
  },
  {
    id: 41,
    question: "¿Qué animal tiene la mejor memoria?",
    options: ["Delfín", "Elefante", "Chimpancé", "Loro"],
    correctAnswerIndex: 1,
  },
  {
    id: 42,
    question: "¿Cuánto puede pesar un elefante africano adulto?",
    options: ["3-4 toneladas", "5-6 toneladas", "6-7 toneladas", "8-9 toneladas"],
    correctAnswerIndex: 2,
  },
  {
    id: 43,
    question: "¿Qué animal puede imitar sonidos humanos?",
    options: ["Loro", "Mirlo", "Ballena beluga", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 44,
    question: "¿Cuál es el pez más rápido del océano?",
    options: ["Atún", "Pez vela", "Marlín", "Tiburón mako"],
    correctAnswerIndex: 1,
  },
  {
    id: 45,
    question: "¿Qué animal tiene el mayor número de dientes?",
    options: ["Tiburón", "Cocodrilo", "Caracol", "Armadillo"],
    correctAnswerIndex: 2,
  },
  {
    id: 46,
    question: "¿Cuánto tiempo puede vivir una ballena azul?",
    options: ["50-60 años", "70-80 años", "80-90 años", "90-100 años"],
    correctAnswerIndex: 2,
  },
  {
    id: 47,
    question: "¿Qué animal tiene el metabolismo más rápido?",
    options: ["Colibrí", "Musaraña", "Murciélago", "Rata"],
    correctAnswerIndex: 0,
  },
  {
    id: 48,
    question: "¿Cuál es el mamífero más pequeño del mundo?",
    options: ["Musaraña etrusca", "Murciélago abejorro", "Lemur ratón", "Todos son correctos"],
    correctAnswerIndex: 3,
  },
  {
    id: 49,
    question: "¿Qué animal puede producir electricidad?",
    options: ["Anguila eléctrica", "Raya eléctrica", "Pez gato eléctrico", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 50,
    question: "¿Cuántas patas tiene un ciempiés?",
    options: ["50", "100", "Varía según la especie", "Siempre 100"],
    correctAnswerIndex: 2,
  },
  {
    id: 51,
    question: "¿Qué animal tiene el sistema de comunicación más complejo?",
    options: ["Delfín", "Ballena jorobada", "Chimpancé", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 52,
    question: "¿Cuál es el pájaro que pone los huevos más grandes?",
    options: ["Avestruz", "Emú", "Cóndor", "Águila"],
    correctAnswerIndex: 0,
  },
  {
    id: 53,
    question: "¿Qué animal puede vivir a mayor profundidad en el océano?",
    options: ["Pulpo dumbo", "Pez abisal", "Medusa abisal", "Todos pueden"],
    correctAnswerIndex: 3,
  },
  {
    id: 54,
    question: "¿Cuántas especies de hormigas existen aproximadamente?",
    options: ["5,000", "10,000", "15,000", "20,000"],
    correctAnswerIndex: 3,
  },
  {
    id: 55,
    question: "¿Qué animal tiene el periodo de hibernación más largo?",
    options: ["Oso pardo", "Ardilla terrestre", "Murciélago", "Erizo"],
    correctAnswerIndex: 1,
  },
  {
    id: 56,
    question: "¿Cuál es el animal más inteligente después del humano?",
    options: ["Delfín", "Chimpancé", "Elefante", "Loro gris africano"],
    correctAnswerIndex: 0,
  },
  {
    id: 57,
    question: "¿Qué animal puede regenerar completamente su cola?",
    options: ["Lagartija", "Salamandra", "Estrella de mar", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 58,
    question: "¿Cuántas especies de tiburones existen?",
    options: ["200", "400", "500", "600"],
    correctAnswerIndex: 2,
  },
  {
    id: 59,
    question: "¿Qué animal tiene la piel más gruesa?",
    options: ["Elefante", "Rinoceronte", "Hipopótamo", "Ballena"],
    correctAnswerIndex: 2,
  },
  {
    id: 60,
    question: "¿Cuál es el animal más longevo?",
    options: ["Ballena de Groenlandia", "Tortuga gigante", "Pez koi", "Erizo de mar rojo"],
    correctAnswerIndex: 3,
  },
  {
    id: 61,
    question: "¿Qué animal puede caminar sobre el agua?",
    options: ["Basilisco", "Araña pescadora", "Gerridae (zapatero)", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 62,
    question: "¿Cuántas veces late el corazón de un colibrí por minuto?",
    options: ["500", "1,000", "1,200", "1,500"],
    correctAnswerIndex: 2,
  },
  {
    id: 63,
    question: "¿Qué animal puede ver la luz ultravioleta?",
    options: ["Abeja", "Mariposa", "Reptiles", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 64,
    question: "¿Cuál es el único pájaro que puede volar hacia atrás?",
    options: ["Colibrí", "Picaflor", "Ambos son correctos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 65,
    question: "¿Qué animal tiene el mayor territorio de caza?",
    options: ["Lobo ártico", "Tigre siberiano", "Águila real", "Leopardo de las nieves"],
    correctAnswerIndex: 0,
  },
  {
    id: 66,
    question: "¿Cuántas crías puede tener un conejo al año?",
    options: ["20-30", "30-40", "40-50", "50-60"],
    correctAnswerIndex: 3,
  },
  {
    id: 67,
    question: "¿Qué animal tiene el sentido del oído más agudo?",
    options: ["Murciélago", "Polilla", "Elefante", "Owl"],
    correctAnswerIndex: 1,
  },
  {
    id: 68,
    question: "¿Cuál es el animal más fuerte en relación a su tamaño?",
    options: ["Escarabajo hércules", "Hormiga", "Escarabajo rinoceronte", "Ácaro"],
    correctAnswerIndex: 0,
  },
  {
    id: 69,
    question: "¿Qué animal puede cambiar de color más rápidamente?",
    options: ["Camaleón", "Pulpo", "Calamar", "Sepia"],
    correctAnswerIndex: 1,
  },
  {
    id: 70,
    question: "¿Cuántos tipos de células tiene una esponja marina?",
    options: ["1", "3", "5", "7"],
    correctAnswerIndex: 1,
  },
  {
    id: 71,
    question: "¿Qué animal tiene el mayor apetito?",
    options: ["Oso hormiguero", "Perezoso", "Panda", "Polilla luna"],
    correctAnswerIndex: 3,
  },
  {
    id: 72,
    question: "¿Cuál es el animal más peligroso para los humanos?",
    options: ["Tiburón", "Hipopótamo", "Mosquito", "Serpiente"],
    correctAnswerIndex: 2,
  },
  {
    id: 73,
    question: "¿Qué animal puede saltar más alto en relación a su tamaño?",
    options: ["Pulga", "Saltamontes", "Rana", "Grillo"],
    correctAnswerIndex: 0,
  },
  {
    id: 74,
    question: "¿Cuántos años puede vivir un loro?",
    options: ["30-40", "40-60", "60-80", "80-100"],
    correctAnswerIndex: 2,
  },
  {
    id: 75,
    question: "¿Qué animal tiene el mayor número de crías en una sola camada?",
    options: ["Tiburón tigre", "Conejo", "Hamster", "Tenia"],
    correctAnswerIndex: 3,
  },
  {
    id: 76,
    question: "¿Cuál es el animal más social?",
    options: ["Delfín", "Elefante", "Chimpancé", "Hormiga"],
    correctAnswerIndex: 3,
  },
  {
    id: 77,
    question: "¿Qué animal puede ver en la oscuridad total?",
    options: ["Murciélago", "Búho", "Gato", "Todos usan otros sentidos"],
    correctAnswerIndex: 3,
  },
  {
    id: 78,
    question: "¿Cuántos huevos pone una tortuga marina en un nido?",
    options: ["50-80", "80-120", "120-150", "150-200"],
    correctAnswerIndex: 1,
  },
  {
    id: 79,
    question: "¿Qué animal tiene el sentido del tacto más desarrollado?",
    options: ["Pulpo", "Estrella de mar", "Elefante", "Ratón"],
    correctAnswerIndex: 0,
  },
  {
    id: 80,
    question: "¿Cuál es el animal más antiguo que aún existe?",
    options: ["Tiburón anguila", "Nautilus", "Celacanto", "Esturión"],
    correctAnswerIndex: 2,
  },
  {
    id: 81,
    question: "¿Qué animal puede sobrevivir a temperaturas extremadamente bajas?",
    options: ["Oso polar", "Pingüino emperador", "Rana de bosque", "Tardígrado"],
    correctAnswerIndex: 3,
  },
  {
    id: 82,
    question: "¿Cuántas especies de primates existen?",
    options: ["150", "250", "350", "450"],
    correctAnswerIndex: 3,
  },
  {
    id: 83,
    question: "¿Qué animal tiene el mayor cerebro en tamaño absoluto?",
    options: ["Elefante", "Ballena azul", "Cachalote", "Orca"],
    correctAnswerIndex: 2,
  },
  {
    id: 84,
    question: "¿Cuál es el animal más lento del mundo?",
    options: ["Perezoso", "Caracol", "Tortuga", "Estrella de mar"],
    correctAnswerIndex: 0,
  },
  {
    id: 85,
    question: "¿Qué animal puede producir luz propia?",
    options: ["Luciérnaga", "Pez linterna", "Calamar luciérnaga", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 86,
    question: "¿Cuántas veces puede picar una abeja?",
    options: ["1 vez", "2 veces", "Varias veces", "Nunca muere al picar"],
    correctAnswerIndex: 0,
  },
  {
    id: 87,
    question: "¿Qué animal tiene el mayor número de especies?",
    options: ["Insectos", "Peces", "Aves", "Mamíferos"],
    correctAnswerIndex: 0,
  },
  {
    id: 88,
    question: "¿Cuál es el animal más abundante en la Tierra?",
    options: ["Hormiga", "Termita", "Nematodo", "Bacteria"],
    correctAnswerIndex: 3,
  },
  {
    id: 89,
    question: "¿Qué animal puede caminar inmediatamente después de nacer?",
    options: ["Potro", "Ternero", "Jirafa", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 90,
    question: "¿Cuántos tipos de células sanguíneas tienen los insectos?",
    options: ["1", "2", "3", "No tienen sangre como los vertebrados"],
    correctAnswerIndex: 3,
  },
  {
    id: 91,
    question: "¿Qué animal tiene el mayor territorio?",
    options: ["Tigre", "Lobo", "Águila calva", "Ballena azul"],
    correctAnswerIndex: 3,
  },
  {
    id: 92,
    question: "¿Cuál es el único mamífero que pone huevos?",
    options: ["Ornitorrinco", "Equidna", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 93,
    question: "¿Qué animal puede vivir a mayor altitud?",
    options: ["Cóndor", "Yak", "Puma", "Araña saltadora del Himalaya"],
    correctAnswerIndex: 3,
  },
  {
    id: 94,
    question: "¿Cuántos años puede vivir una medusa inmortal?",
    options: ["100 años", "500 años", "1,000 años", "Teóricamente para siempre"],
    correctAnswerIndex: 3,
  },
  {
    id: 95,
    question: "¿Qué animal tiene el sistema inmune más fuerte?",
    options: ["Tiburón", "Cocodrilo", "Tardígrado", "Lombriz de tierra"],
    correctAnswerIndex: 0,
  },
  {
    id: 96,
    question: "¿Cuál es el animal con el metabolismo más lento?",
    options: ["Perezoso", "Tortuga", "Cocodrilo", "Ballena"],
    correctAnswerIndex: 0,
  },
  {
    id: 97,
    question: "¿Qué animal puede detectar campos magnéticos?",
    options: ["Paloma", "Tiburón", "Tortuga marina", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 98,
    question: "¿Cuántas especies se extinguen cada día aproximadamente?",
    options: ["10-20", "50-100", "150-200", "200-300"],
    correctAnswerIndex: 2,
  },
  {
    id: 99,
    question: "¿Qué animal tiene la mayor diversidad de especies?",
    options: ["Escarabajos", "Mariposas", "Aves", "Peces"],
    correctAnswerIndex: 0,
  },
  {
    id: 100,
    question: "¿Cuál es el animal más resistente a la radiación?",
    options: ["Cucaracha", "Tardígrado", "Bacteria Deinococcus radiodurans", "Escorpión"],
    correctAnswerIndex: 2,
  },
];