// IDs del 1101 al 1200
export const QUESTION_NATURALEZA = [
  {
    id: 1101,
    question: "¿Qué planeta es conocido como el Planeta Rojo?",
    options: ["Venus", "Marte", "Júpiter", "Saturno"],
    correctAnswerIndex: 1,
  },
  {
    id: 1102,
    question: "¿Cuál es el animal más grande del mundo?",
    options: ["Elefante", "Ballena azul", "Tiburón blanco", "Jirafa"],
    correctAnswerIndex: 1,
  },
  {
    id: 1103,
    question: "¿Qué gas respiramos los humanos principalmente?",
    options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Helio"],
    correctAnswerIndex: 0,
  },
  {
    id: 1104,
    question: "¿Qué parte de la planta produce semillas?",
    options: ["Hoja", "Flor", "Tallo", "Raíz"],
    correctAnswerIndex: 1,
  },
  {
    id: 1105,
    question: "¿Cuál es el bosque más grande del mundo?",
    options: ["Amazonas", "Bosque Negro", "Taiga", "Selva de Congo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1106,
    question: "¿Qué animal pone huevos?",
    options: ["Perro", "Gato", "Gallina", "Vaca"],
    correctAnswerIndex: 2,
  },
  {
    id: 1107,
    question: "¿Qué recurso natural usamos para encender fuego fácilmente?",
    options: ["Papel", "Piedra", "Madera", "Gasolina"],
    correctAnswerIndex: 2,
  },
  {
    id: 1108,
    question: "¿Qué animal es conocido por su caparazón duro?",
    options: ["Tortuga", "León", "Elefante", "Delfín"],
    correctAnswerIndex: 0,
  },
  {
    id: 1109,
    question: "¿Cuál es la principal fuente de energía para las plantas?",
    options: ["Luz solar", "Agua", "Viento", "Tierra"],
    correctAnswerIndex: 0,
  },
  {
    id: 1110,
    question: "¿Qué animal puede volar?",
    options: ["Pato", "Perro", "Oso", "Elefante"],
    correctAnswerIndex: 0,
  },

  {
    id: 1111,
    question: "¿Qué animal es conocido como el rey de la selva?",
    options: ["Tigre", "León", "Elefante", "Jaguar"],
    correctAnswerIndex: 1,
  },
  {
    id: 1112,
    question: "¿Qué planeta está más cerca del Sol?",
    options: ["Venus", "Mercurio", "Tierra", "Marte"],
    correctAnswerIndex: 1,
  },
  {
    id: 1113,
    question: "¿Qué líquido necesitan todas las plantas para vivir?",
    options: ["Aceite", "Agua", "Leche", "Jugo"],
    correctAnswerIndex: 1,
  },
  {
    id: 1114,
    question: "¿Qué animal vive en la Antártida y es un gran nadador?",
    options: ["Pingüino", "Oso polar", "Foca", "Ballena"],
    correctAnswerIndex: 0,
  },
  {
    id: 1115,
    question: "¿Cuál es el ave que no puede volar?",
    options: ["Avestruz", "Águila", "Paloma", "Loro"],
    correctAnswerIndex: 0,
  },
  {
    id: 1116,
    question: "¿Qué fruto crece en un cactus?",
    options: ["Manzana", "Nopal", "Pera", "Cereza"],
    correctAnswerIndex: 1,
  },
  {
    id: 1117,
    question: "¿Qué animal es famoso por cambiar de color?",
    options: ["Camaleón", "Perro", "Elefante", "Tigre"],
    correctAnswerIndex: 0,
  },
  {
    id: 1118,
    question: "¿Qué planeta tiene anillos visibles?",
    options: ["Marte", "Saturno", "Venus", "Mercurio"],
    correctAnswerIndex: 1,
  },
  {
    id: 1119,
    question: "¿Qué animal dice 'miau'?",
    options: ["Perro", "Gato", "Vaca", "Caballo"],
    correctAnswerIndex: 1,
  },
  {
    id: 1120,
    question: "¿Cuál es el océano más grande del mundo?",
    options: ["Atlántico", "Índico", "Pacífico", "Ártico"],
    correctAnswerIndex: 2,
  },

  {
    id: 1121,
    question: "¿Qué insecto produce miel?",
    options: ["Abeja", "Mariposa", "Mosca", "Hormiga"],
    correctAnswerIndex: 0,
  },
  {
    id: 1122,
    question: "¿Qué animal tiene trompa larga?",
    options: ["Elefante", "Rinoceronte", "Jirafa", "Cocodrilo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1123,
    question: "¿Qué planeta es el más grande del sistema solar?",
    options: ["Júpiter", "Saturno", "Neptuno", "Urano"],
    correctAnswerIndex: 0,
  },
  {
    id: 1124,
    question: "¿Qué animal dice 'guau'?",
    options: ["Gato", "Perro", "Pato", "Vaca"],
    correctAnswerIndex: 1,
  },
  {
    id: 1125,
    question: "¿Qué tipo de animal es un delfín?",
    options: ["Pez", "Mamífero", "Reptil", "Anfibio"],
    correctAnswerIndex: 1,
  },
  {
    id: 1126,
    question: "¿Cuál es la principal fuente de luz del planeta Tierra?",
    options: ["Luna", "Sol", "Estrellas", "Electricidad"],
    correctAnswerIndex: 1,
  },
  {
    id: 1127,
    question: "¿Qué animal construye colmenas?",
    options: ["Abeja", "Hormiga", "Araña", "Castor"],
    correctAnswerIndex: 0,
  },
  {
    id: 1128,
    question: "¿Qué animal es el más lento?",
    options: ["Tortuga", "Caracol", "Perezoso", "Elefante"],
    correctAnswerIndex: 1,
  },
  {
    id: 1129,
    question: "¿Qué animal es conocido por su cuello largo?",
    options: ["Elefante", "Jirafa", "Canguro", "Camello"],
    correctAnswerIndex: 1,
  },
  {
    id: 1130,
    question: "¿Qué parte de la planta absorbe agua del suelo?",
    options: ["Hoja", "Raíz", "Tallo", "Flor"],
    correctAnswerIndex: 1,
  },

  {
    id: 1131,
    question: "¿Qué animal vive en un nido y pone huevos?",
    options: ["Pato", "Pollo", "Gallina", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1132,
    question: "¿Qué animal es el más rápido en tierra?",
    options: ["León", "Guepardo", "Tigre", "Caballo"],
    correctAnswerIndex: 1,
  },
  {
    id: 1133,
    question: "¿Qué planeta es azul por su agua?",
    options: ["Tierra", "Neptuno", "Marte", "Venus"],
    correctAnswerIndex: 0,
  },
  {
    id: 1134,
    question: "¿Qué animal vive en el agua y tiene aletas?",
    options: ["Pez", "Delfín", "Tiburón", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1135,
    question: "¿Qué gas usan las plantas para hacer fotosíntesis?",
    options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"],
    correctAnswerIndex: 1,
  },
  {
    id: 1136,
    question: "¿Qué animal vive en la selva y es muy fuerte?",
    options: ["Gorila", "Elefante", "Tigre", "Jaguar"],
    correctAnswerIndex: 0,
  },
  {
    id: 1137,
    question: "¿Qué animal vive en el desierto y almacena agua?",
    options: ["Camello", "Elefante", "Cebra", "León"],
    correctAnswerIndex: 0,
  },
  {
    id: 1138,
    question: "¿Qué animal produce lana?",
    options: ["Oveja", "Cabra", "Conejo", "Vaca"],
    correctAnswerIndex: 0,
  },
  {
    id: 1139,
    question: "¿Qué animal es conocido por su caparazón y lentitud?",
    options: ["Tortuga", "Caracol", "Perezoso", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 1140,
    question: "¿Qué fruto crece en un árbol?",
    options: ["Manzana", "Lechuga", "Zanahoria", "Pepino"],
    correctAnswerIndex: 0,
  },

  {
    id: 1141,
    question: "¿Qué animal es famoso por su cola que puede enrollar?",
    options: ["Mono", "Canguro", "Camaleón", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 1142,
    question: "¿Qué tipo de animal es un pingüino?",
    options: ["Ave", "Mamífero", "Reptil", "Pez"],
    correctAnswerIndex: 0,
  },
  {
    id: 1143,
    question: "¿Qué animal tiene rayas blancas y negras?",
    options: ["Cebra", "Tigre", "Panda", "Leopardo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1144,
    question: "¿Qué animal es conocido por su habilidad para saltar muy alto?",
    options: ["Canguro", "Elefante", "Jirafa", "Tortuga"],
    correctAnswerIndex: 0,
  },
  {
    id: 1145,
    question: "¿Qué animal tiene trompa y colmillos largos?",
    options: ["Elefante", "Rinoceronte", "Mamut", "Hipopótamo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1146,
    question: "¿Qué planta usamos para hacer papel?",
    options: ["Bambú", "Árbol", "Cactus", "Hierba"],
    correctAnswerIndex: 1,
  },
  {
    id: 1147,
    question: "¿Qué animal es conocido por su caparazón duro y lentitud?",
    options: ["Tortuga", "Caracol", "Perezoso", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1148,
    question: "¿Qué animal vive en el polo norte y tiene pelo blanco?",
    options: ["Oso polar", "Pingüino", "Foca", "Lobo ártico"],
    correctAnswerIndex: 0,
  },
  {
    id: 1149,
    question: "¿Qué animal es famoso por su habilidad para cambiar de color?",
    options: ["Camaleón", "Lagarto", "Rana", "Serpiente"],
    correctAnswerIndex: 0,
  },
  {
    id: 1150,
    question: "¿Qué animal produce leche que los humanos consumen?",
    options: ["Vaca", "Caballo", "Cebra", "Oveja"],
    correctAnswerIndex: 0,
  },
  {
    id: 1151,
    question: "¿Qué planta es conocida por sus flores amarillas y se sigue el sol?",
    options: ["Girasol", "Tulipán", "Rosa", "Lirio"],
    correctAnswerIndex: 0,
  },
  {
    id: 1152,
    question: "¿Qué animal vive en la granja y da huevos?",
    options: ["Gallina", "Vaca", "Cerdo", "Oveja"],
    correctAnswerIndex: 0,
  },
  {
    id: 1153,
    question: "¿Qué insecto tiene alas y colores brillantes?",
    options: ["Mariposa", "Abeja", "Mosquito", "Hormiga"],
    correctAnswerIndex: 0,
  },
  {
    id: 1154,
    question: "¿Qué animal es conocido por su risa y vive en los bosques de África?",
    options: ["Hiena", "Mono", "Elefante", "León"],
    correctAnswerIndex: 0,
  },
  {
    id: 1155,
    question: "¿Qué animal se balancea de árbol en árbol y come plátanos?",
    options: ["Mono", "Koala", "Oso", "Canguro"],
    correctAnswerIndex: 0,
  },
  {
    id: 1156,
    question: "¿Qué animal tiene una lengua larga y atrapa insectos?",
    options: ["Camaleón", "Rana", "Tortuga", "Lagarto"],
    correctAnswerIndex: 0,
  },
  {
    id: 1157,
    question: "¿Qué animal vive en colmenas y produce miel?",
    options: ["Abeja", "Mosca", "Mariposa", "Avispa"],
    correctAnswerIndex: 0,
  },
  {
    id: 1158,
    question: "¿Qué árbol da bellotas?",
    options: ["Roble", "Pino", "Abeto", "Cerezo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1159,
    question: "¿Qué animal es el más alto del mundo?",
    options: ["Jirafa", "Elefante", "Camello", "Cebra"],
    correctAnswerIndex: 0,
  },
  {
    id: 1160,
    question: "¿Qué animal vive en el océano y tiene ocho brazos?",
    options: ["Pulpo", "Calamar", "Medusa", "Pez payaso"],
    correctAnswerIndex: 0,
  },
  {
    id: 1161,
    question: "¿Qué insecto es conocido por su aguijón?",
    options: ["Abeja", "Mariposa", "Escarabajo", "Libélula"],
    correctAnswerIndex: 0,
  },
  {
    id: 1162,
    question: "¿Qué animal es blanco y negro y vive en China?",
    options: ["Panda", "Oso polar", "Pingüino", "Zebra"],
    correctAnswerIndex: 0,
  },
  {
    id: 1163,
    question: "¿Qué planta produce frutos cítricos como la naranja?",
    options: ["Naranjo", "Manzano", "Cerezo", "Peral"],
    correctAnswerIndex: 0,
  },
  {
    id: 1164,
    question: "¿Qué animal es conocido por su largo cuello y manchas marrones?",
    options: ["Jirafa", "Cebra", "Elefante", "Camello"],
    correctAnswerIndex: 0,
  },
  {
    id: 1165,
    question: "¿Qué animal es grande, gris y tiene trompa?",
    options: ["Elefante", "Hipopótamo", "Rinoceronte", "Oso"],
    correctAnswerIndex: 0,
  },
  {
    id: 1166,
    question: "¿Qué animal se esconde en su caparazón?",
    options: ["Tortuga", "Caracol", "Cangrejo", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1167,
    question: "¿Qué animal nada y tiene aletas?",
    options: ["Pez", "Delfín", "Tiburón", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1168,
    question: "¿Qué planta tiene espinas y crece en el desierto?",
    options: ["Cactus", "Rosa", "Lirio", "Tulipán"],
    correctAnswerIndex: 0,
  },
  {
    id: 1169,
    question: "¿Qué animal produce lana?",
    options: ["Oveja", "Vaca", "Conejo", "Cabra"],
    correctAnswerIndex: 0,
  },
  {
    id: 1170,
    question: "¿Qué fruta es amarilla y alargada?",
    options: ["Plátano", "Manzana", "Pera", "Naranja"],
    correctAnswerIndex: 0,
  },
  {
    id: 1171,
    question: "¿Qué animal vive en madrigueras y tiene orejas largas?",
    options: ["Conejo", "Zorro", "Tortuga", "Ratón"],
    correctAnswerIndex: 0,
  },
  {
    id: 1172,
    question: "¿Qué animal dice 'oink'?",
    options: ["Cerdo", "Vaca", "Gato", "Perro"],
    correctAnswerIndex: 0,
  },
  {
    id: 1173,
    question: "¿Qué animal es negro y vuela de noche?",
    options: ["Murciélago", "Cuervo", "Lechuza", "Paloma"],
    correctAnswerIndex: 0,
  },
  {
    id: 1174,
    question: "¿Qué animal vive en el agua y tiene concha dura?",
    options: ["Cangrejo", "Caracol", "Tortuga", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1175,
    question: "¿Qué ave es conocida por repetir sonidos humanos?",
    options: ["Loro", "Águila", "Paloma", "Pingüino"],
    correctAnswerIndex: 0,
  },
  {
    id: 1176,
    question: "¿Qué animal vive en la granja y hace 'muuu'?",
    options: ["Vaca", "Cerdo", "Oveja", "Caballo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1177,
    question: "¿Qué planta tiene flores rojas y espinas?",
    options: ["Rosa", "Tulipán", "Girasol", "Orquídea"],
    correctAnswerIndex: 0,
  },
  {
    id: 1178,
    question: "¿Qué animal es famoso por saltar y llevar su cría en una bolsa?",
    options: ["Canguro", "Koala", "Oso", "Mono"],
    correctAnswerIndex: 0,
  },
  {
    id: 1179,
    question: "¿Qué animal vive en el agua y puede ser muy grande?",
    options: ["Ballena", "Tiburón", "Delfín", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1180,
    question: "¿Qué árbol produce piñas?",
    options: ["Pino", "Roble", "Abeto", "Sauce"],
    correctAnswerIndex: 0,
  },
  {
    id: 1181,
    question: "¿Qué animal es famoso por construir presas?",
    options: ["Castor", "Castor canadiense", "Nutria", "Todos los anteriores"],
    correctAnswerIndex: 0,
  },
  {
    id: 1182,
    question: "¿Qué animal vive en colmenas y tiene aguijón?",
    options: ["Abeja", "Avispa", "Hormiga", "Mosca"],
    correctAnswerIndex: 0,
  },
  {
    id: 1183,
    question: "¿Qué animal tiene orejas largas y vive en madrigueras?",
    options: ["Conejo", "Zorro", "Lobo", "Ratón"],
    correctAnswerIndex: 0,
  },
  {
    id: 1184,
    question: "¿Qué fruta es roja y pequeña y crece en plantas bajas?",
    options: ["Fresa", "Manzana", "Cereza", "Frambuesa"],
    correctAnswerIndex: 0,
  },
  {
    id: 1185,
    question: "¿Qué animal vive en ríos y tiene dientes grandes?",
    options: ["Cocodrilo", "Hipopótamo", "Tiburón", "Todos los anteriores"],
    correctAnswerIndex: 0,
  },
  {
    id: 1186,
    question: "¿Qué animal es muy lento y cuelga de los árboles?",
    options: ["Perezoso", "Tortuga", "Caracol", "Elefante"],
    correctAnswerIndex: 0,
  },
  {
    id: 1187,
    question: "¿Qué animal tiene trompa larga y orejas grandes?",
    options: ["Elefante", "Rinoceronte", "Mamut", "Hipopótamo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1188,
    question: "¿Qué planta crece en el desierto y almacena agua?",
    options: ["Cactus", "Rosa", "Lirio", "Tulipán"],
    correctAnswerIndex: 0,
  },
  {
    id: 1189,
    question: "¿Qué animal es blanco y negro y vive en China?",
    options: ["Panda", "Oso polar", "Pingüino", "Zebra"],
    correctAnswerIndex: 0,
  },
  {
    id: 1190,
    question: "¿Qué fruta es amarilla y alargada?",
    options: ["Plátano", "Naranja", "Limón", "Melón"],
    correctAnswerIndex: 0,
  },
  {
    id: 1191,
    question: "¿Qué animal tiene caparazón y se mueve lentamente?",
    options: ["Tortuga", "Caracol", "Perezoso", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1192,
    question: "¿Qué ave no puede volar y vive en el hemisferio sur?",
    options: ["Pingüino", "Avestruz", "Kiwi", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1193,
    question: "¿Qué animal dice 'quiá'?",
    options: ["Gallina", "Pato", "Gallo", "Oveja"],
    correctAnswerIndex: 1,
  },
  {
    id: 1194,
    question: "¿Qué animal vive en el océano y tiene concha?",
    options: ["Cangrejo", "Caracol", "Tortuga marina", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 1195,
    question: "¿Qué árbol tiene hojas verdes todo el año?",
    options: ["Pino", "Roble", "Álamo", "Cerezo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1196,
    question: "¿Qué animal es famoso por su larga lengua y atrapa insectos?",
    options: ["Camaleón", "Rana", "Lagarto", "Serpiente"],
    correctAnswerIndex: 0,
  },
  {
    id: 1197,
    question: "¿Qué animal vive en madrigueras y tiene orejas largas?",
    options: ["Conejo", "Zorro", "Ratón", "Topo"],
    correctAnswerIndex: 0,
  },
  {
    id: 1198,
    question: "¿Qué fruta es roja y crece en arbustos?",
    options: ["Fresa", "Cereza", "Manzana", "Frambuesa"],
    correctAnswerIndex: 0,
  },
  {
    id: 1199,
    question: "¿Qué animal vive en el hielo y nada muy bien?",
    options: ["Pingüino", "Oso polar", "Foca", "Ballena"],
    correctAnswerIndex: 0,
  },
  {
    id: 1200,
    question: "¿Qué animal construye nidos en los árboles y puede volar?",
    options: ["Pájaro", "Murciélago", "Mariposa", "Águila"], 
    correctAnswerIndex: 0,
  },
];
