// IDs del 301 al 400
export const QUESTION_CINE = [
  {
    id: 301,
    question: "¿Quién dirigió la película Titanic?",
    options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Ridley Scott"],
    correctAnswerIndex: 1,
  },
  {
    id: 302,
    question: "¿En qué año se estrenó Jurassic Park?",
    options: ["1990", "1993", "1996", "1989"],
    correctAnswerIndex: 1,
  },
  {
    id: 303,
    question: "¿Qué actor interpretó a Iron Man en el MCU?",
    options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"],
    correctAnswerIndex: 1,
  },
  {
    id: 304,
    question: "¿Cómo se llama el hobbit protagonista de El Señor de los Anillos?",
    options: ["Frodo Bolsón", "Bilbo Bolsón", "Sam Gamyi", "Pippin"],
    correctAnswerIndex: 0,
  },
  {
    id: 305,
    question: "¿Qué película ganó el Oscar a Mejor Película en 2020?",
    options: ["1917", "Joker", "Parásitos", "Once Upon a Time in Hollywood"],
    correctAnswerIndex: 2,
  },
  {
    id: 306,
    question: "¿Quién interpretó al Joker en The Dark Knight?",
    options: ["Joaquin Phoenix", "Heath Ledger", "Jack Nicholson", "Jared Leto"],
    correctAnswerIndex: 1,
  },
  {
    id: 307,
    question: "¿De qué país es la película Parásitos?",
    options: ["Japón", "China", "Corea del Sur", "Tailandia"],
    correctAnswerIndex: 2,
  },
  {
    id: 308,
    question: "¿Qué saga cinematográfica incluye a Luke Skywalker?",
    options: ["Star Trek", "Star Wars", "Matrix", "Dune"],
    correctAnswerIndex: 1,
  },
  {
    id: 309,
    question: "¿Quién dirigió Pulp Fiction?",
    options: ["Martin Scorsese", "Quentin Tarantino", "Guy Ritchie", "Francis Ford Coppola"],
    correctAnswerIndex: 1,
  },
  {
    id: 310,
    question: "¿Qué película animada presenta al personaje Simba?",
    options: ["Bambi", "El Rey León", "Madagascar", "Zootopia"],
    correctAnswerIndex: 1,
  },

  {
    id: 311,
    question: "¿Qué actor interpretó a Jack Sparrow?",
    options: ["Orlando Bloom", "Johnny Depp", "Leonardo DiCaprio", "Brad Pitt"],
    correctAnswerIndex: 1,
  },
  {
    id: 312,
    question: "¿Qué película es famosa por la frase 'Hasta la vista, baby'?",
    options: ["Terminator 2", "Rocky", "Rambo", "Matrix"],
    correctAnswerIndex: 0,
  },
  {
    id: 313,
    question: "¿Quién dirigió El Padrino?",
    options: ["Brian De Palma", "Martin Scorsese", "Francis Ford Coppola", "Stanley Kubrick"],
    correctAnswerIndex: 2,
  },
  {
    id: 314,
    question: "¿Qué actriz protagonizó Pretty Woman?",
    options: ["Julia Roberts", "Sandra Bullock", "Meg Ryan", "Nicole Kidman"],
    correctAnswerIndex: 0,
  },
  {
    id: 315,
    question: "¿Qué película trata sobre sueños dentro de sueños?",
    options: ["Matrix", "Origen (Inception)", "Interstellar", "Tenet"],
    correctAnswerIndex: 1,
  },
  {
    id: 316,
    question: "¿Quién interpretó a Wolverine?",
    options: ["Hugh Jackman", "Ryan Reynolds", "Chris Pratt", "Ben Affleck"],
    correctAnswerIndex: 0,
  },
  {
    id: 317,
    question: "¿Qué película ganó el Oscar a Mejor Película en 1994?",
    options: ["Pulp Fiction", "Forrest Gump", "Cadena perpetua", "Cuatro bodas y un funeral"],
    correctAnswerIndex: 1,
  },
  {
    id: 318,
    question: "¿Qué director es conocido por películas como El Resplandor y 2001?",
    options: ["Alfred Hitchcock", "Stanley Kubrick", "Ridley Scott", "Tim Burton"],
    correctAnswerIndex: 1,
  },
  {
    id: 319,
    question: "¿En qué película aparece el personaje Neo?",
    options: ["Blade Runner", "Matrix", "Tron", "Minority Report"],
    correctAnswerIndex: 1,
  },
  {
    id: 320,
    question: "¿Qué actor protagonizó Gladiador?",
    options: ["Russell Crowe", "Brad Pitt", "Mel Gibson", "Tom Cruise"],
    correctAnswerIndex: 0,
  },

  {
    id: 321,
    question: "¿Qué película animada fue la primera de Pixar?",
    options: ["Bichos", "Toy Story", "Cars", "Monsters Inc."],
    correctAnswerIndex: 1,
  },
  {
    id: 322,
    question: "¿Quién dirigió Avatar?",
    options: ["Peter Jackson", "James Cameron", "George Lucas", "Michael Bay"],
    correctAnswerIndex: 1,
  },
  {
    id: 323,
    question: "¿Qué actor interpreta a Batman en The Dark Knight?",
    options: ["Ben Affleck", "Christian Bale", "Michael Keaton", "Val Kilmer"],
    correctAnswerIndex: 1,
  },
  {
    id: 324,
    question: "¿Qué película se desarrolla en Pandora?",
    options: ["Avatar", "Dune", "Star Wars", "Star Trek"],
    correctAnswerIndex: 0,
  },
  {
    id: 325,
    question: "¿Qué director creó la trilogía original de Star Wars?",
    options: ["Steven Spielberg", "George Lucas", "J.J. Abrams", "Ron Howard"],
    correctAnswerIndex: 1,
  },
  {
    id: 326,
    question: "¿Qué película ganó el Oscar a Mejor Película en 1997?",
    options: ["Titanic", "El paciente inglés", "Fargo", "Jerry Maguire"],
    correctAnswerIndex: 0,
  },
  {
    id: 327,
    question: "¿Qué actriz interpretó a Katniss Everdeen?",
    options: ["Emma Stone", "Jennifer Lawrence", "Scarlett Johansson", "Natalie Portman"],
    correctAnswerIndex: 1,
  },
  {
    id: 328,
    question: "¿Qué película es famosa por el personaje Darth Vader?",
    options: ["Star Trek", "Star Wars", "Alien", "Predator"],
    correctAnswerIndex: 1,
  },
  {
    id: 329,
    question: "¿Quién dirigió El Señor de los Anillos?",
    options: ["Peter Jackson", "James Cameron", "Christopher Nolan", "Ridley Scott"],
    correctAnswerIndex: 0,
  },
  {
    id: 330,
    question: "¿Qué actor protagonizó Forrest Gump?",
    options: ["Tom Hanks", "Robin Williams", "Matt Damon", "Brad Pitt"],
    correctAnswerIndex: 0,
  },

  {
    id: 331,
    question: "¿Qué película trata sobre un parque de dinosaurios?",
    options: ["King Kong", "Jurassic Park", "Godzilla", "Ice Age"],
    correctAnswerIndex: 1,
  },
  {
    id: 332,
    question: "¿Qué director es conocido por películas de estilo oscuro y gótico?",
    options: ["Tim Burton", "Wes Anderson", "Steven Spielberg", "Guy Ritchie"],
    correctAnswerIndex: 0,
  },
  {
    id: 333,
    question: "¿Qué película tiene como protagonista a un tiburón gigante?",
    options: ["Deep Blue Sea", "Jaws", "The Meg", "Sharknado"],
    correctAnswerIndex: 1,
  },
  {
    id: 334,
    question: "¿Qué actriz protagonizó Black Swan?",
    options: ["Natalie Portman", "Anne Hathaway", "Emma Watson", "Mila Kunis"],
    correctAnswerIndex: 0,
  },
  {
    id: 335,
    question: "¿Quién interpretó a Rocky Balboa?",
    options: ["Arnold Schwarzenegger", "Sylvester Stallone", "Jean-Claude Van Damme", "Bruce Willis"],
    correctAnswerIndex: 1,
  },
  {
    id: 336,
    question: "¿Qué película animada tiene al robot Wall-E?",
    options: ["Robots", "Wall-E", "Big Hero 6", "Cars"],
    correctAnswerIndex: 1,
  },
  {
    id: 337,
    question: "¿Qué director es conocido por Inception e Interstellar?",
    options: ["Denis Villeneuve", "Christopher Nolan", "James Cameron", "Zack Snyder"],
    correctAnswerIndex: 1,
  },
  {
    id: 338,
    question: "¿Qué película trata sobre viajes en el tiempo con un DeLorean?",
    options: ["Matrix", "Volver al Futuro", "Looper", "Tenet"],
    correctAnswerIndex: 1,
  },
  {
    id: 339,
    question: "¿Qué actor interpretó a Deadpool?",
    options: ["Ryan Reynolds", "Hugh Jackman", "Chris Evans", "Paul Rudd"],
    correctAnswerIndex: 0,
  },
  {
    id: 340,
    question: "¿Qué película ganó el Oscar a Mejor Película en 2003?",
    options: ["Chicago", "El Señor de los Anillos: El Retorno del Rey", "Gangs of New York", "The Pianist"],
    correctAnswerIndex: 1,
  },

  {
    id: 341,
    question: "¿Qué actriz interpretó a Hermione Granger?",
    options: ["Emma Watson", "Emma Stone", "Keira Knightley", "Natalie Portman"],
    correctAnswerIndex: 0,
  },
  {
    id: 342,
    question: "¿Qué película es protagonizada por un payaso llamado Pennywise?",
    options: ["Joker", "It", "Saw", "Annabelle"],
    correctAnswerIndex: 1,
  },
  {
    id: 343,
    question: "¿Quién dirigió La La Land?",
    options: ["Damien Chazelle", "Wes Anderson", "James Cameron", "Todd Phillips"],
    correctAnswerIndex: 0,
  },
  {
    id: 344,
    question: "¿Qué actor protagonizó Misión Imposible?",
    options: ["Tom Cruise", "Matt Damon", "Brad Pitt", "Keanu Reeves"],
    correctAnswerIndex: 0,
  },
  {
    id: 345,
    question: "¿Qué película animada ocurre en la mente de una niña?",
    options: ["Coco", "Intensamente", "Up", "Soul"],
    correctAnswerIndex: 1,
  },
  {
    id: 346,
    question: "¿Qué director es conocido como el 'maestro del suspenso'?",
    options: ["Stanley Kubrick", "Alfred Hitchcock", "Orson Welles", "Brian De Palma"],
    correctAnswerIndex: 1,
  },
  {
    id: 347,
    question: "¿Qué película presenta a un androide llamado T-800?",
    options: ["Robocop", "Terminator", "Blade Runner", "Alien"],
    correctAnswerIndex: 1,
  },
  {
    id: 348,
    question: "¿Qué actor interpretó a Hannibal Lecter?",
    options: ["Anthony Hopkins", "Robert De Niro", "Al Pacino", "Jack Nicholson"],
    correctAnswerIndex: 0,
  },
  {
    id: 349,
    question: "¿Qué película trata sobre la vida de Freddie Mercury?",
    options: ["Rocketman", "Bohemian Rhapsody", "Yesterday", "Elvis"],
    correctAnswerIndex: 1,
  },
  {
    id: 350,
    question: "¿Qué director dirigió Dune (2021)?",
    options: ["Ridley Scott", "Denis Villeneuve", "Christopher Nolan", "James Cameron"],
    correctAnswerIndex: 1,
  },

  {
    id: 351,
    question: "¿Qué actor protagonizó El Renacido?",
    options: ["Leonardo DiCaprio", "Brad Pitt", "Christian Bale", "Matt Damon"],
    correctAnswerIndex: 0,
  },
  {
    id: 352,
    question: "¿Qué película se ambienta en un hotel embrujado?",
    options: ["It", "El Resplandor", "Insidious", "Hereditary"],
    correctAnswerIndex: 1,
  },
  {
    id: 353,
    question: "¿Qué actor interpretó a Spider-Man en el MCU?",
    options: ["Andrew Garfield", "Tobey Maguire", "Tom Holland", "Jake Gyllenhaal"],
    correctAnswerIndex: 2,
  },
  {
    id: 354,
    question: "¿Qué película ganó el Oscar a Mejor Película en 2014?",
    options: ["Birdman", "Boyhood", "Whiplash", "The Grand Budapest Hotel"],
    correctAnswerIndex: 0,
  },
  {
    id: 355,
    question: "¿Qué película trata sobre un músico de jazz y un baterista?",
    options: ["La La Land", "Whiplash", "Birdman", "Soul"],
    correctAnswerIndex: 1,
  },
  {
    id: 356,
    question: "¿Quién dirigió Taxi Driver?",
    options: ["Martin Scorsese", "Francis Ford Coppola", "Stanley Kubrick", "Brian De Palma"],
    correctAnswerIndex: 0,
  },
  {
    id: 357,
    question: "¿Qué actor interpretó a Thanos?",
    options: ["Josh Brolin", "Mark Ruffalo", "Dave Bautista", "Vin Diesel"],
    correctAnswerIndex: 0,
  },
  {
    id: 358,
    question: "¿Qué película animada se desarrolla en el mundo de los muertos?",
    options: ["Coco", "Soul", "Up", "Luca"],
    correctAnswerIndex: 0,
  },
  {
    id: 359,
    question: "¿Qué actor protagonizó El Lobo de Wall Street?",
    options: ["Leonardo DiCaprio", "Johnny Depp", "Brad Pitt", "George Clooney"],
    correctAnswerIndex: 0,
  },
  {
    id: 360,
    question: "¿Qué película es famosa por el personaje Gollum?",
    options: ["Harry Potter", "El Hobbit", "El Señor de los Anillos", "Narnia"],
    correctAnswerIndex: 2,
  },

  {
    id: 361,
    question: "¿Qué director dirigió E.T.?",
    options: ["George Lucas", "Steven Spielberg", "Ridley Scott", "James Cameron"],
    correctAnswerIndex: 1,
  },
  {
    id: 362,
    question: "¿Qué actor interpretó a James Bond en Skyfall?",
    options: ["Pierce Brosnan", "Daniel Craig", "Roger Moore", "Sean Connery"],
    correctAnswerIndex: 1,
  },
  {
    id: 363,
    question: "¿Qué película se desarrolla en Wakanda?",
    options: ["Avengers", "Black Panther", "Thor", "Doctor Strange"],
    correctAnswerIndex: 1,
  },
  {
    id: 364,
    question: "¿Qué actriz ganó el Oscar por La La Land?",
    options: ["Emma Stone", "Natalie Portman", "Jennifer Lawrence", "Scarlett Johansson"],
    correctAnswerIndex: 0,
  },
  {
    id: 365,
    question: "¿Qué película trata sobre un boxeador?",
    options: ["Creed", "Rocky", "Raging Bull", "Todas"],
    correctAnswerIndex: 3,
  },
  {
    id: 366,
    question: "¿Qué director es conocido por películas simétricas y coloridas?",
    options: ["Wes Anderson", "Tim Burton", "Guillermo del Toro", "Sofia Coppola"],
    correctAnswerIndex: 0,
  },
  {
    id: 367,
    question: "¿Qué actor protagonizó Matrix?",
    options: ["Keanu Reeves", "Tom Cruise", "Will Smith", "Brad Pitt"],
    correctAnswerIndex: 0,
  },
  {
    id: 368,
    question: "¿Qué película ganó el Oscar a Mejor Película en 2019?",
    options: ["Green Book", "Roma", "Bohemian Rhapsody", "La Favorita"],
    correctAnswerIndex: 0,
  },
  {
    id: 369,
    question: "¿Qué director dirigió El Laberinto del Fauno?",
    options: ["Guillermo del Toro", "Alfonso Cuarón", "Alejandro G. Iñárritu", "Pedro Almodóvar"],
    correctAnswerIndex: 0,
  },
  {
    id: 370,
    question: "¿Qué película trata sobre un virus mortal?",
    options: ["Outbreak", "Contagion", "28 Days Later", "Todas"],
    correctAnswerIndex: 3,
  },

  {
    id: 371,
    question: "¿Qué actor interpretó a Joker en 2019?",
    options: ["Heath Ledger", "Joaquin Phoenix", "Jared Leto", "Jack Nicholson"],
    correctAnswerIndex: 1,
  },
  {
    id: 372,
    question: "¿Qué película animada tiene emociones como personajes?",
    options: ["Up", "Intensamente", "Soul", "Toy Story"],
    correctAnswerIndex: 1,
  },
  {
    id: 373,
    question: "¿Qué director dirigió Alien?",
    options: ["James Cameron", "Ridley Scott", "David Fincher", "Tim Burton"],
    correctAnswerIndex: 1,
  },
  {
    id: 374,
    question: "¿Qué actor protagonizó Blade Runner?",
    options: ["Harrison Ford", "Ryan Gosling", "Rutger Hauer", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 375,
    question: "¿Qué película trata sobre un pianista durante la Segunda Guerra Mundial?",
    options: ["El Pianista", "La Lista de Schindler", "1917", "Dunkerque"],
    correctAnswerIndex: 0,
  },
  {
    id: 376,
    question: "¿Qué director dirigió El Caballero Oscuro?",
    options: ["Zack Snyder", "Christopher Nolan", "Tim Burton", "Joss Whedon"],
    correctAnswerIndex: 1,
  },
  {
    id: 377,
    question: "¿Qué película presenta al personaje Buzz Lightyear?",
    options: ["Toy Story", "Wall-E", "Up", "Cars"],
    correctAnswerIndex: 0,
  },
  {
    id: 378,
    question: "¿Qué actor protagonizó Piratas del Caribe?",
    options: ["Orlando Bloom", "Johnny Depp", "Geoffrey Rush", "Javier Bardem"],
    correctAnswerIndex: 1,
  },
  {
    id: 379,
    question: "¿Qué película ganó el Oscar a Mejor Película en 2018?",
    options: ["La Forma del Agua", "Dunkerque", "Get Out", "Call Me by Your Name"],
    correctAnswerIndex: 0,
  },
  {
    id: 380,
    question: "¿Qué director dirigió Interestelar?",
    options: ["Denis Villeneuve", "Christopher Nolan", "James Cameron", "Ridley Scott"],
    correctAnswerIndex: 1,
  },

  {
    id: 381,
    question: "¿Qué película trata sobre un sueño compartido?",
    options: ["Origen", "Matrix", "Tenet", "Looper"],
    correctAnswerIndex: 0,
  },
  {
    id: 382,
    question: "¿Qué actor interpretó a Superman en Man of Steel?",
    options: ["Henry Cavill", "Brandon Routh", "Christopher Reeve", "Ben Affleck"],
    correctAnswerIndex: 0,
  },
  {
    id: 383,
    question: "¿Qué película animada tiene a un ratón cocinero?",
    options: ["Ratatouille", "Chef", "Bichos", "Stuart Little"],
    correctAnswerIndex: 0,
  },
  {
    id: 384,
    question: "¿Qué director dirigió Gravity?",
    options: ["Alfonso Cuarón", "Alejandro G. Iñárritu", "Guillermo del Toro", "James Cameron"],
    correctAnswerIndex: 0,
  },
  {
    id: 385,
    question: "¿Qué película trata sobre un robot policía?",
    options: ["Terminator", "Robocop", "Blade Runner", "I, Robot"],
    correctAnswerIndex: 1,
  },
  {
    id: 386,
    question: "¿Qué actor protagonizó El Gran Gatsby (2013)?",
    options: ["Leonardo DiCaprio", "Brad Pitt", "Tobey Maguire", "Tom Hardy"],
    correctAnswerIndex: 0,
  },
  {
    id: 387,
    question: "¿Qué película trata sobre la creación de Facebook?",
    options: ["Steve Jobs", "The Social Network", "Jobs", "Silicon Valley"],
    correctAnswerIndex: 1,
  },
  {
    id: 388,
    question: "¿Qué director dirigió La Lista de Schindler?",
    options: ["Steven Spielberg", "Roman Polanski", "Martin Scorsese", "Ridley Scott"],
    correctAnswerIndex: 0,
  },
  {
    id: 389,
    question: "¿Qué actor interpretó a Indiana Jones?",
    options: ["Harrison Ford", "Tom Selleck", "Mel Gibson", "Kevin Costner"],
    correctAnswerIndex: 0,
  },
  {
    id: 390,
    question: "¿Qué película animada ocurre en el océano?",
    options: ["Moana", "Buscando a Nemo", "Luca", "Todas"],
    correctAnswerIndex: 3,
  },

  {
    id: 391,
    question: "¿Qué director dirigió Reservoir Dogs?",
    options: ["Quentin Tarantino", "Guy Ritchie", "Martin Scorsese", "Kevin Smith"],
    correctAnswerIndex: 0,
  },
  {
    id: 392,
    question: "¿Qué película presenta al personaje Tony Montana?",
    options: ["Casino", "Scarface", "Heat", "Goodfellas"],
    correctAnswerIndex: 1,
  },
  {
    id: 393,
    question: "¿Qué actor protagonizó El Silencio de los Inocentes?",
    options: ["Anthony Hopkins", "Al Pacino", "Robert De Niro", "Jack Nicholson"],
    correctAnswerIndex: 0,
  },
  {
    id: 394,
    question: "¿Qué película trata sobre un payaso criminal?",
    options: ["It", "Joker", "The Mask", "Saw"],
    correctAnswerIndex: 1,
  },
  {
    id: 395,
    question: "¿Qué director dirigió Mad Max: Fury Road?",
    options: ["George Miller", "Ridley Scott", "James Cameron", "Christopher Nolan"],
    correctAnswerIndex: 0,
  },
  {
    id: 396,
    question: "¿Qué actor interpretó a Maximus?",
    options: ["Russell Crowe", "Joaquin Phoenix", "Gerard Butler", "Brad Pitt"],
    correctAnswerIndex: 0,
  },
  {
    id: 397,
    question: "¿Qué película trata sobre un hotel para monstruos?",
    options: ["Monsters Inc.", "Hotel Transylvania", "Shrek", "Sing"],
    correctAnswerIndex: 1,
  },
  {
    id: 398,
    question: "¿Qué director dirigió Fight Club?",
    options: ["David Fincher", "Christopher Nolan", "Quentin Tarantino", "Guy Ritchie"],
    correctAnswerIndex: 0,
  },
  {
    id: 399,
    question: "¿Qué actor protagonizó El Club de la Pelea?",
    options: ["Brad Pitt", "Edward Norton", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 400,
    question: "¿Qué película ganó el Oscar a Mejor Película en 1999?",
    options: ["La Vida es Bella", "Salvar al Soldado Ryan", "Shakespeare in Love", "El Sexto Sentido"],
    correctAnswerIndex: 2,
  },
];
