// IDs del 801 al 900
export const QUESTION_HISTORIA = [
  {
    id: 801,
    question: "¿En qué año Cristóbal Colón llegó a América?",
    options: ["1490", "1492", "1500", "1495"],
    correctAnswerIndex: 1,
  },
  {
    id: 802,
    question: "¿Quién fue el primer emperador romano?",
    options: ["Julio César", "Augusto", "Nerón", "Calígula"],
    correctAnswerIndex: 1,
  },
  {
    id: 803,
    question: "¿Qué imperio construyó Machu Picchu?",
    options: ["Azteca", "Maya", "Inca", "Tolteca"],
    correctAnswerIndex: 2,
  },
  {
    id: 804,
    question: "¿En qué año terminó la Segunda Guerra Mundial?",
    options: ["1944", "1945", "1946", "1947"],
    correctAnswerIndex: 1,
  },
  {
    id: 805,
    question: "¿Quién escribió la Ilíada y la Odisea?",
    options: ["Sófocles", "Homero", "Platón", "Aristóteles"],
    correctAnswerIndex: 1,
  },
  {
    id: 806,
    question: "¿Cuál fue la primera civilización en escribir?",
    options: ["Egipcia", "Mesopotámica", "China", "Griega"],
    correctAnswerIndex: 1,
  },
  {
    id: 807,
    question: "¿Qué año marcó la caída del Imperio Romano de Occidente?",
    options: ["410", "476", "500", "455"],
    correctAnswerIndex: 1,
  },
  {
    id: 808,
    question: "¿Quién fue conocido como 'El Libertador' en América del Sur?",
    options: ["Simón Bolívar", "José de San Martín", "Antonio José de Sucre", "Bernardo O’Higgins"],
    correctAnswerIndex: 0,
  },
  {
    id: 809,
    question: "¿Cuál fue la primera Constitución de Estados Unidos?",
    options: ["Declaración de Independencia", "Constitución de 1787", "Bill of Rights", "Artículos de Confederación"],
    correctAnswerIndex: 3,
  },
  {
    id: 810,
    question: "¿Qué invento se atribuye a Johannes Gutenberg?",
    options: ["Telescopio", "Imprenta", "Reloj mecánico", "Máquina de vapor"],
    correctAnswerIndex: 1,
  },

  {
    id: 811,
    question: "¿Quién pintó la Capilla Sixtina?",
    options: ["Leonardo da Vinci", "Miguel Ángel", "Rafael", "Donatello"],
    correctAnswerIndex: 1,
  },
  {
    id: 812,
    question: "¿Qué evento inició la Revolución Francesa?",
    options: ["La toma de la Bastilla", "El juicio a Luis XVI", "La independencia de Estados Unidos", "El golpe de Napoleón"],
    correctAnswerIndex: 0,
  },
  {
    id: 813,
    question: "¿Quién lideró la independencia de México?",
    options: ["Miguel Hidalgo", "Benito Juárez", "José María Morelos", "Antonio López de Santa Anna"],
    correctAnswerIndex: 0,
  },
  {
    id: 814,
    question: "¿Qué civilización construyó las pirámides de Egipto?",
    options: ["Griega", "Mesopotámica", "Egipcia", "Romana"],
    correctAnswerIndex: 2,
  },
  {
    id: 815,
    question: "¿Quién fue el primer presidente de Estados Unidos?",
    options: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"],
    correctAnswerIndex: 1,
  },
  {
    id: 816,
    question: "¿Qué muro separaba Berlín Oriental y Occidental?",
    options: ["Muro de Berlín", "Muro de los Lamentos", "Gran Muralla China", "Muro de Adriano"],
    correctAnswerIndex: 0,
  },
  {
    id: 817,
    question: "¿Qué guerra tuvo lugar entre 1914 y 1918?",
    options: ["Segunda Guerra Mundial", "Primera Guerra Mundial", "Guerra Fría", "Guerra de Crimea"],
    correctAnswerIndex: 1,
  },
  {
    id: 818,
    question: "¿Qué imperio gobernaba gran parte de Europa durante el siglo XIX?",
    options: ["Imperio Otomano", "Imperio Austrohúngaro", "Imperio Británico", "Imperio Ruso"],
    correctAnswerIndex: 2,
  },
  {
    id: 819,
    question: "¿Quién fue Napoleón Bonaparte?",
    options: ["Rey de España", "Emperador francés", "General británico", "Revolucionario ruso"],
    correctAnswerIndex: 1,
  },
  {
    id: 820,
    question: "¿Cuál fue el primer hombre en pisar la Luna?",
    options: ["Yuri Gagarin", "Buzz Aldrin", "Neil Armstrong", "Michael Collins"],
    correctAnswerIndex: 2,
  },

  {
    id: 821,
    question: "¿Qué civilización construyó Chichén Itzá?",
    options: ["Azteca", "Maya", "Inca", "Olmeca"],
    correctAnswerIndex: 1,
  },
  {
    id: 822,
    question: "¿En qué año se firmó la Declaración de Independencia de Estados Unidos?",
    options: ["1776", "1789", "1800", "1750"],
    correctAnswerIndex: 0,
  },
  {
    id: 823,
    question: "¿Qué líder sudafricano luchó contra el apartheid?",
    options: ["Nelson Mandela", "Desmond Tutu", "Robert Mugabe", "Julius Nyerere"],
    correctAnswerIndex: 0,
  },
  {
    id: 824,
    question: "¿Qué imperio cayó en 1453 con la toma de Constantinopla?",
    options: ["Imperio Bizantino", "Imperio Otomano", "Imperio Romano", "Imperio Persa"],
    correctAnswerIndex: 0,
  },
  {
    id: 825,
    question: "¿Quién fue conocido como el 'Rey Sol'?",
    options: ["Luis XIII", "Luis XIV", "Luis XV", "Carlos V"],
    correctAnswerIndex: 1,
  },
  {
    id: 826,
    question: "¿Qué guerra enfrentó a Norteamérica y Gran Bretaña entre 1775 y 1783?",
    options: ["Guerra de Secesión", "Revolución Americana", "Guerra Franco-India", "Guerra de 1812"],
    correctAnswerIndex: 1,
  },
  {
    id: 827,
    question: "¿Qué civilización creó el calendario maya?",
    options: ["Azteca", "Maya", "Inca", "Tolteca"],
    correctAnswerIndex: 1,
  },
  {
    id: 828,
    question: "¿En qué año comenzó la Revolución Industrial?",
    options: ["1700", "1760", "1800", "1850"],
    correctAnswerIndex: 1,
  },
  {
    id: 829,
    question: "¿Quién fue Juana de Arco?",
    options: ["Reina de Francia", "Heroína y santa francesa", "Princesa inglesa", "General alemán"],
    correctAnswerIndex: 1,
  },
  {
    id: 830,
    question: "¿Qué imperio construyó la Gran Muralla China?",
    options: ["Qin", "Han", "Ming", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },

  {
    id: 831,
    question: "¿Quién fue conocido como 'El zar rojo'?",
    options: ["Pedro el Grande", "Lenin", "Stalin", "Nikolái II"],
    correctAnswerIndex: 2,
  },
  {
    id: 832,
    question: "¿En qué año cayó el Muro de Berlín?",
    options: ["1987", "1989", "1991", "1993"],
    correctAnswerIndex: 1,
  },
  {
    id: 833,
    question: "¿Qué faraón egipcio tuvo la tumba descubierta por Howard Carter?",
    options: ["Tutankamón", "Ramsés II", "Keops", "Akenatón"],
    correctAnswerIndex: 0,
  },
  {
    id: 834,
    question: "¿Qué civilización creó los jeroglíficos?",
    options: ["Egipcia", "Mesopotámica", "Maya", "Griega"],
    correctAnswerIndex: 0,
  },
  {
    id: 835,
    question: "¿Quién fue el líder nazi durante la Segunda Guerra Mundial?",
    options: ["Joseph Stalin", "Adolf Hitler", "Benito Mussolini", "Francisco Franco"],
    correctAnswerIndex: 1,
  },
  {
    id: 836,
    question: "¿Qué acontecimiento ocurrió el 11 de septiembre de 2001?",
    options: ["Atentados en Nueva York y Washington", "Inicio de la Guerra de Irak", "Fin de la Guerra Fría", "Huracán Katrina"],
    correctAnswerIndex: 0,
  },
  {
    id: 837,
    question: "¿Qué tratado puso fin a la Primera Guerra Mundial?",
    options: ["Tratado de Versalles", "Tratado de París", "Tratado de Berlín", "Tratado de Tordesillas"],
    correctAnswerIndex: 0,
  },
  {
    id: 838,
    question: "¿Quién fue emperador de Francia durante las guerras napoleónicas?",
    options: ["Luis XVI", "Napoleón Bonaparte", "Robespierre", "Carlos X"],
    correctAnswerIndex: 1,
  },
  {
    id: 839,
    question: "¿Qué civilización construyó Tikal?",
    options: ["Azteca", "Maya", "Inca", "Olmeca"],
    correctAnswerIndex: 1,
  },
  {
    id: 840,
    question: "¿Qué rey inglés firmó la Carta Magna?",
    options: ["Juan I", "Enrique VIII", "Eduardo III", "Ricardo Corazón de León"],
    correctAnswerIndex: 0,
  },

    {
    id: 841,
    question: "¿Qué evento dio inicio a la Segunda Guerra Mundial?",
    options: ["Invasión de Polonia", "Ataque a Pearl Harbor", "Batalla de Stalingrado", "Caída del Muro de Berlín"],
    correctAnswerIndex: 0,
  },
  {
    id: 842,
    question: "¿Quién fue el primer presidente de la Unión Soviética?",
    options: ["Lenin", "Stalin", "Trotsky", "Khrushchev"],
    correctAnswerIndex: 0,
  },
  {
    id: 843,
    question: "¿Qué ciudad fue dividida por un muro entre 1961 y 1989?",
    options: ["Varsovia", "Berlín", "París", "Viena"],
    correctAnswerIndex: 1,
  },
  {
    id: 844,
    question: "¿Qué reina británica tuvo el reinado más largo antes de Isabel II?",
    options: ["Victoria", "Ana", "Isabel I", "María Tudor"],
    correctAnswerIndex: 0,
  },
  {
    id: 845,
    question: "¿Qué tratado puso fin a la guerra entre Estados Unidos y México?",
    options: ["Tratado de Guadalupe Hidalgo", "Tratado de Versalles", "Tratado de París", "Tratado de Tordesillas"],
    correctAnswerIndex: 0,
  },
  {
    id: 846,
    question: "¿Qué imperio construyó Petra, en Jordania?",
    options: ["Romano", "Nabateo", "Persa", "Egipcio"],
    correctAnswerIndex: 1,
  },
  {
    id: 847,
    question: "¿Quién lideró la Revolución Rusa de 1917?",
    options: ["Lenin", "Stalin", "Kerensky", "Trotsky"],
    correctAnswerIndex: 0,
  },
  {
    id: 848,
    question: "¿Qué guerra enfrentó a Atenas y Esparta?",
    options: ["Guerras Médicas", "Guerra del Peloponeso", "Guerra de Troya", "Guerras Púnicas"],
    correctAnswerIndex: 1,
  },
  {
    id: 849,
    question: "¿Qué civilización construyó la ciudad de Teotihuacán?",
    options: ["Azteca", "Maya", "Tolteca", "Olmeca"],
    correctAnswerIndex: 2,
  },
  {
    id: 850,
    question: "¿Qué país sufrió la Guerra de los Cien Años?",
    options: ["España e Inglaterra", "Francia e Inglaterra", "Italia y Francia", "Portugal e Inglaterra"],
    correctAnswerIndex: 1,
  },
  {
    id: 851,
    question: "¿Quién fue el líder de la Revolución Cubana?",
    options: ["Fidel Castro", "Che Guevara", "Raúl Castro", "Hugo Chávez"],
    correctAnswerIndex: 0,
  },
  {
    id: 852,
    question: "¿En qué año comenzó la Revolución Francesa?",
    options: ["1789", "1776", "1804", "1799"],
    correctAnswerIndex: 0,
  },
  {
    id: 853,
    question: "¿Qué civilización construyó el Templo de Kukulcán?",
    options: ["Azteca", "Maya", "Inca", "Tolteca"],
    correctAnswerIndex: 1,
  },
  {
    id: 854,
    question: "¿Qué rey francés fue ejecutado durante la Revolución Francesa?",
    options: ["Luis XIV", "Luis XVI", "Luis XV", "Luis XIII"],
    correctAnswerIndex: 1,
  },
  {
    id: 855,
    question: "¿Quién fue el autor del manifiesto comunista?",
    options: ["Karl Marx y Friedrich Engels", "Lenin", "Stalin", "Trotsky"],
    correctAnswerIndex: 0,
  },
  {
    id: 856,
    question: "¿Qué evento marcó el fin del Imperio Otomano?",
    options: ["Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra de Crimea", "Guerra de los Balcanes"],
    correctAnswerIndex: 0,
  },
  {
    id: 857,
    question: "¿Qué tratado dividió el mundo entre España y Portugal en 1494?",
    options: ["Tratado de Tordesillas", "Tratado de Versalles", "Tratado de París", "Tratado de Guadalupe Hidalgo"],
    correctAnswerIndex: 0,
  },
  {
    id: 858,
    question: "¿Quién fundó la ciudad de Roma según la leyenda?",
    options: ["Rómulo y Remo", "Julio César", "Augusto", "César Augusto"],
    correctAnswerIndex: 0,
  },
  {
    id: 859,
    question: "¿Qué evento marcó la caída del Imperio Bizantino?",
    options: ["Invasión mongola", "Toma de Constantinopla", "Revolución Francesa", "Caída de Roma"],
    correctAnswerIndex: 1,
  },
  {
    id: 860,
    question: "¿Quién fue el líder de Alemania durante la Primera Guerra Mundial?",
    options: ["Wilhelm II", "Bismarck", "Hitler", "Hindenburg"],
    correctAnswerIndex: 0,
  },
  {
    id: 861,
    question: "¿Qué movimiento cultural floreció en Europa en los siglos XV y XVI?",
    options: ["Renacimiento", "Barroco", "Romanticismo", "Ilustración"],
    correctAnswerIndex: 0,
  },
  {
    id: 862,
    question: "¿Quién fue el primer emperador de China?",
    options: ["Qin Shi Huang", "Han Wudi", "Kublai Khan", "Mao Zedong"],
    correctAnswerIndex: 0,
  },
  {
    id: 863,
    question: "¿Qué civilización construyó la ciudad de Cuzco?",
    options: ["Inca", "Azteca", "Maya", "Tolteca"],
    correctAnswerIndex: 0,
  },
  {
    id: 864,
    question: "¿En qué año se abolió la esclavitud en Estados Unidos?",
    options: ["1860", "1863", "1870", "1850"],
    correctAnswerIndex: 1,
  },
  {
    id: 865,
    question: "¿Qué imperio estaba liderado por Gengis Kan?",
    options: ["Mongol", "Persa", "Otomanos", "Chino"],
    correctAnswerIndex: 0,
  },
  {
    id: 866,
    question: "¿Qué ciudad fue destruida por el Vesubio en el año 79 d.C.?",
    options: ["Roma", "Herculano y Pompeya", "Cartago", "Atenas"],
    correctAnswerIndex: 1,
  },
  {
    id: 867,
    question: "¿Quién fue el principal líder de la independencia de Argentina?",
    options: ["José de San Martín", "Simón Bolívar", "Miguel Hidalgo", "Antonio José de Sucre"],
    correctAnswerIndex: 0,
  },
  {
    id: 868,
    question: "¿Qué líder francés llegó al poder tras el golpe de Estado del 18 de Brumario?",
    options: ["Luis XVI", "Napoleón Bonaparte", "Robespierre", "Carlos X"],
    correctAnswerIndex: 1,
  },
  {
    id: 869,
    question: "¿Qué revolución ocurrió en Rusia en 1917?",
    options: ["Revolución Rusa", "Revolución Industrial", "Revolución Francesa", "Revolución Americana"],
    correctAnswerIndex: 0,
  },
  {
    id: 870,
    question: "¿Qué tratado dividió África entre potencias europeas en 1884?",
    options: ["Conferencia de Berlín", "Tratado de Versalles", "Tratado de París", "Tratado de Tordesillas"],
    correctAnswerIndex: 0,
  },
  {
    id: 871,
    question: "¿Quién fue conocido como 'El Rey Sol' en Francia?",
    options: ["Luis XIII", "Luis XIV", "Luis XV", "Carlos V"],
    correctAnswerIndex: 1,
  },
  {
    id: 872,
    question: "¿Qué imperio fue dirigido por Alejandro Magno?",
    options: ["Macedonio", "Persa", "Egipcio", "Romano"],
    correctAnswerIndex: 0,
  },
  {
    id: 873,
    question: "¿Qué ciudad italiana fue cuna del Renacimiento?",
    options: ["Roma", "Florencia", "Venecia", "Milán"],
    correctAnswerIndex: 1,
  },
  {
    id: 874,
    question: "¿Qué conflicto se conoce como la Guerra de Secesión?",
    options: ["Guerra Civil de Estados Unidos", "Primera Guerra Mundial", "Guerra de Vietnam", "Revolución Mexicana"],
    correctAnswerIndex: 0,
  },
  {
    id: 875,
    question: "¿Quién fue el faraón durante la construcción de la Gran Pirámide de Guiza?",
    options: ["Keops", "Tutankamón", "Ramsés II", "Akenatón"],
    correctAnswerIndex: 0,
  },
  {
    id: 876,
    question: "¿Qué acontecimiento marcó el inicio de la Edad Moderna?",
    options: ["Caída de Constantinopla", "Descubrimiento de América", "Reforma Protestante", "Todas las anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 877,
    question: "¿Qué tratado terminó la Guerra de los Treinta Años?",
    options: ["Tratado de Westfalia", "Tratado de Versalles", "Tratado de París", "Tratado de Tordesillas"],
    correctAnswerIndex: 0,
  },
  {
    id: 878,
    question: "¿Quién fue emperador romano durante el incendio de Roma en el año 64 d.C.?",
    options: ["Nerón", "Calígula", "Tiberio", "Augusto"],
    correctAnswerIndex: 0,
  },
  {
    id: 879,
    question: "¿Qué explorador circunnavegó por primera vez el mundo?",
    options: ["Cristóbal Colón", "Fernando de Magallanes", "Vasco da Gama", "James Cook"],
    correctAnswerIndex: 1,
  },
  {
    id: 880,
    question: "¿Quién fue conocido como 'El Libertador del Perú'?",
    options: ["José de San Martín", "Simón Bolívar", "Antonio José de Sucre", "Bernardo O’Higgins"],
    correctAnswerIndex: 0,
  },
  {
    id: 881,
    question: "¿Qué civilización precolombina habitó el actual territorio de México antes de los aztecas?",
    options: ["Maya", "Olmeca", "Inca", "Tolteca"],
    correctAnswerIndex: 1,
  },
  {
    id: 882,
    question: "¿Quién escribió 'El Príncipe'?",
    options: ["Maquiavelo", "Tomás Moro", "Montesquieu", "Rousseau"],
    correctAnswerIndex: 0,
  },
  {
    id: 883,
    question: "¿Qué emperador romano proclamó el cristianismo como religión oficial?",
    options: ["Nerón", "Constantino", "Julio César", "Trajano"],
    correctAnswerIndex: 1,
  },
  {
    id: 884,
    question: "¿Qué guerra enfrentó a Inglaterra contra Argentina en 1982?",
    options: ["Guerra de Malvinas", "Guerra del Golfo", "Guerra de Crimea", "Guerra de los Balcanes"],
    correctAnswerIndex: 0,
  },
  {
    id: 885,
    question: "¿Qué país fue liderado por Benito Mussolini?",
    options: ["Alemania", "Italia", "España", "Francia"],
    correctAnswerIndex: 1,
  },
  {
    id: 886,
    question: "¿Quién descubrió América?",
    options: ["Cristóbal Colón", "Américo Vespucio", "Magallanes", "Vasco Núñez de Balboa"],
    correctAnswerIndex: 0,
  },
  {
    id: 887,
    question: "¿Qué líder francés fue ejecutado en la Revolución Francesa?",
    options: ["Luis XVI", "Robespierre", "Napoleón", "Luis XIV"],
    correctAnswerIndex: 0,
  },
  {
    id: 888,
    question: "¿Qué ciudad fue sede de los Juegos Olímpicos en 1936?",
    options: ["Tokio", "Berlín", "París", "Los Ángeles"],
    correctAnswerIndex: 1,
  },
  {
    id: 889,
    question: "¿Qué conflicto enfrentó a Estados Unidos y Vietnam?",
    options: ["Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra de Vietnam", "Guerra de Corea"],
    correctAnswerIndex: 2,
  },
  {
    id: 890,
    question: "¿Qué imperio existió en Mesopotamia?",
    options: ["Asirio", "Babilónico", "Sumerio", "Todos los anteriores"],
    correctAnswerIndex: 3,
  },
  {
    id: 891,
    question: "¿Quién fue líder del Reino Unido durante la Segunda Guerra Mundial?",
    options: ["Winston Churchill", "Neville Chamberlain", "Margaret Thatcher", "Tony Blair"],
    correctAnswerIndex: 0,
  },
  {
    id: 892,
    question: "¿Qué evento marcó el inicio de la Edad Contemporánea?",
    options: ["Revolución Francesa", "Caída de Roma", "Descubrimiento de América", "Guerra de los Cien Años"],
    correctAnswerIndex: 0,
  },
  {
    id: 893,
    question: "¿Quién fue líder de la Revolución Mexicana tras la muerte de Madero?",
    options: ["Emiliano Zapata", "Pancho Villa", "Victoriano Huerta", "Venustiano Carranza"],
    correctAnswerIndex: 2,
  },
  {
    id: 894,
    question: "¿Qué imperio estaba gobernado por los zares?",
    options: ["Ruso", "Chino", "Mongol", "Persa"],
    correctAnswerIndex: 0,
  },
  {
    id: 895,
    question: "¿Quién fue Cleopatra?",
    options: ["Reina de Egipto", "Emperatriz romana", "Princesa griega", "Sacerdotisa maya"],
    correctAnswerIndex: 0,
  },
  {
    id: 896,
    question: "¿Qué conflicto fue entre Estados del Norte y del Sur en EE. UU.?",
    options: ["Guerra de Independencia", "Guerra Civil", "Guerra de Secesión", "Guerra de Vietnam"],
    correctAnswerIndex: 1,
  },
  {
    id: 897,
    question: "¿Qué líder mongol fundó el imperio más grande del mundo?",
    options: ["Gengis Kan", "Kublai Kan", "Tamerlán", "Hulagu Kan"],
    correctAnswerIndex: 0,
  },
  {
    id: 898,
    question: "¿Qué civilización construyó los templos de Angkor Wat?",
    options: ["Maya", "Jemer", "Inca", "Azteca"],
    correctAnswerIndex: 1,
  },
  {
    id: 899,
    question: "¿Qué país fue dividido tras la Segunda Guerra Mundial?",
    options: ["Alemania", "Polonia", "Japón", "Italia"],
    correctAnswerIndex: 0,
  },
  {
    id: 900,
    question: "¿Quién fue conocido como el 'Padre de la Patria' en México?",
    options: ["Miguel Hidalgo", "José María Morelos", "Benito Juárez", "Vicente Guerrero"],
    correctAnswerIndex: 0,
  },

];
