// IDs del 201 al 300
export const QUESTION_CIENCIA = [
  {
    id: 201,
    question: "¿Cuál es el planeta más cercano al Sol?",
    options: ["Venus", "Mercurio", "Marte", "Tierra"],
    correctAnswerIndex: 1,
  },
  {
    id: 202,
    question: "¿Qué gas es el más abundante en la atmósfera terrestre?",
    options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"],
    correctAnswerIndex: 2,
  },
  {
    id: 203,
    question: "¿Cuál es la unidad básica de la vida?",
    options: ["Átomo", "Molécula", "Célula", "Tejido"],
    correctAnswerIndex: 2,
  },
  {
    id: 204,
    question: "¿Qué órgano bombea la sangre en el cuerpo humano?",
    options: ["Pulmón", "Cerebro", "Corazón", "Riñón"],
    correctAnswerIndex: 2,
  },
  {
    id: 205,
    question: "¿Qué tipo de energía proviene del Sol?",
    options: ["Eólica", "Solar", "Geotérmica", "Nuclear"],
    correctAnswerIndex: 1,
  },
  {
    id: 206,
    question: "¿Cuál es el metal más ligero?",
    options: ["Hierro", "Aluminio", "Litio", "Plomo"],
    correctAnswerIndex: 2,
  },
  {
    id: 207,
    question: "¿Quién propuso la teoría de la relatividad?",
    options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"],
    correctAnswerIndex: 1,
  },
  {
    id: 208,
    question: "¿Qué planeta es conocido como el planeta rojo?",
    options: ["Júpiter", "Marte", "Venus", "Saturno"],
    correctAnswerIndex: 1,
  },
  {
    id: 209,
    question: "¿A qué temperatura se congela el agua?",
    options: ["100°C", "0°C", "10°C", "-50°C"],
    correctAnswerIndex: 1,
  },
  {
    id: 210,
    question: "¿Qué parte de la planta realiza la fotosíntesis?",
    options: ["Raíz", "Tallo", "Hoja", "Flor"],
    correctAnswerIndex: 2,
  },

  {
    id: 211,
    question: "¿Qué tipo de animal es el delfín?",
    options: ["Pez", "Mamífero", "Reptil", "Anfibio"],
    correctAnswerIndex: 1,
  },
  {
    id: 212,
    question: "¿Cuál es el hueso más largo del cuerpo humano?",
    options: ["Húmero", "Fémur", "Radio", "Tibia"],
    correctAnswerIndex: 1,
  },
  {
    id: 213,
    question: "¿Qué instrumento se usa para medir la temperatura?",
    options: ["Barómetro", "Termómetro", "Anemómetro", "Higrómetro"],
    correctAnswerIndex: 1,
  },
  {
    id: 214,
    question: "¿Qué vitamina produce el cuerpo con la luz solar?",
    options: ["Vitamina A", "Vitamina B", "Vitamina C", "Vitamina D"],
    correctAnswerIndex: 3,
  },
  {
    id: 215,
    question: "¿Qué fuerza mantiene a los planetas en órbita?",
    options: ["Magnetismo", "Electricidad", "Gravedad", "Fricción"],
    correctAnswerIndex: 2,
  },
  {
    id: 216,
    question: "¿Qué órgano filtra la sangre en el cuerpo humano?",
    options: ["Pulmones", "Hígado", "Riñones", "Estómago"],
    correctAnswerIndex: 2,
  },
  {
    id: 217,
    question: "¿Cómo se llama el paso de líquido a gas?",
    options: ["Condensación", "Fusión", "Evaporación", "Solidificación"],
    correctAnswerIndex: 2,
  },
  {
    id: 218,
    question: "¿Qué planeta tiene los anillos más visibles?",
    options: ["Júpiter", "Saturno", "Urano", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 219,
    question: "¿Cuál es el órgano principal del sistema nervioso?",
    options: ["Corazón", "Pulmón", "Cerebro", "Riñón"],
    correctAnswerIndex: 2,
  },
  {
    id: 220,
    question: "¿Qué gas inhalamos para vivir?",
    options: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Helio"],
    correctAnswerIndex: 0,
  },

  {
    id: 221,
    question: "¿Qué ciencia estudia los seres vivos?",
    options: ["Física", "Química", "Biología", "Astronomía"],
    correctAnswerIndex: 2,
  },
  {
    id: 222,
    question: "¿Cuál es el planeta más grande del sistema solar?",
    options: ["Saturno", "Júpiter", "Urano", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 223,
    question: "¿Qué órgano se encarga de la respiración?",
    options: ["Pulmones", "Corazón", "Riñones", "Hígado"],
    correctAnswerIndex: 0,
  },
  {
    id: 224,
    question: "¿Qué sustancia permite a las plantas ser verdes?",
    options: ["Melanina", "Clorofila", "Hemoglobina", "Proteína"],
    correctAnswerIndex: 1,
  },
  {
    id: 225,
    question: "¿Cuál es el grupo sanguíneo donante universal?",
    options: ["A", "B", "AB", "O"],
    correctAnswerIndex: 3,
  },
  {
    id: 226,
    question: "¿Qué planeta es el más frío del sistema solar?",
    options: ["Neptuno", "Urano", "Saturno", "Marte"],
    correctAnswerIndex: 1,
  },
  {
    id: 227,
    question: "¿Qué órgano produce la insulina?",
    options: ["Hígado", "Páncreas", "Riñón", "Estómago"],
    correctAnswerIndex: 1,
  },
  {
    id: 228,
    question: "¿Qué energía se obtiene del viento?",
    options: ["Solar", "Eólica", "Hidráulica", "Térmica"],
    correctAnswerIndex: 1,
  },
  {
    id: 229,
    question: "¿Qué parte del ojo regula la entrada de luz?",
    options: ["Retina", "Pupila", "Córnea", "Cristalino"],
    correctAnswerIndex: 1,
  },
  {
    id: 230,
    question: "¿Qué planeta es famoso por su gran mancha roja?",
    options: ["Marte", "Júpiter", "Saturno", "Neptuno"],
    correctAnswerIndex: 1,
  },

  {
    id: 231,
    question: "¿Qué ciencia estudia los terremotos?",
    options: ["Geología", "Meteorología", "Sismología", "Astronomía"],
    correctAnswerIndex: 2,
  },
  {
    id: 232,
    question: "¿Cómo se llaman los animales que ponen huevos?",
    options: ["Vivíparos", "Ovíparos", "Mamíferos", "Marsupiales"],
    correctAnswerIndex: 1,
  },
  {
    id: 233,
    question: "¿Qué protege al cerebro?",
    options: ["Costillas", "Cráneo", "Columna", "Piel"],
    correctAnswerIndex: 1,
  },
  {
    id: 234,
    question: "¿Qué planeta tarda más en girar alrededor del Sol?",
    options: ["Saturno", "Urano", "Neptuno", "Júpiter"],
    correctAnswerIndex: 2,
  },
  {
    id: 235,
    question: "¿Qué órgano permite el sentido de la vista?",
    options: ["Nariz", "Oído", "Ojo", "Lengua"],
    correctAnswerIndex: 2,
  },
  {
    id: 236,
    question: "¿Qué energía se obtiene del agua en movimiento?",
    options: ["Solar", "Eólica", "Hidráulica", "Nuclear"],
    correctAnswerIndex: 2,
  },
  {
    id: 237,
    question: "¿Qué gas expulsamos al respirar?",
    options: ["Oxígeno", "Helio", "Dióxido de carbono", "Nitrógeno"],
    correctAnswerIndex: 2,
  },
  {
    id: 238,
    question: "¿Qué planeta es conocido como el planeta azul?",
    options: ["Neptuno", "Urano", "Tierra", "Venus"],
    correctAnswerIndex: 2,
  },
  {
    id: 239,
    question: "¿Qué órgano controla el equilibrio?",
    options: ["Cerebro", "Oído interno", "Pulmón", "Corazón"],
    correctAnswerIndex: 1,
  },
  {
    id: 240,
    question: "¿Qué tipo de animal es la rana?",
    options: ["Reptil", "Mamífero", "Anfibio", "Ave"],
    correctAnswerIndex: 2,
  },

  {
    id: 241,
    question: "¿Cuál es el satélite natural de la Tierra?",
    options: ["Marte", "La Luna", "Venus", "El Sol"],
    correctAnswerIndex: 1,
  },
  {
    id: 242,
    question: "¿Qué órgano digiere los alimentos?",
    options: ["Pulmón", "Estómago", "Riñón", "Corazón"],
    correctAnswerIndex: 1,
  },
  {
    id: 243,
    question: "¿Qué tipo de energía produce una pila?",
    options: ["Eléctrica", "Solar", "Eólica", "Térmica"],
    correctAnswerIndex: 0,
  },
  {
    id: 244,
    question: "¿Qué planeta tiene el día más largo?",
    options: ["Mercurio", "Venus", "Marte", "Júpiter"],
    correctAnswerIndex: 1,
  },
  {
    id: 245,
    question: "¿Qué órgano produce la bilis?",
    options: ["Páncreas", "Hígado", "Estómago", "Riñón"],
    correctAnswerIndex: 1,
  },
  {
    id: 246,
    question: "¿Qué animal es un invertebrado?",
    options: ["Perro", "Serpiente", "Pulpo", "Águila"],
    correctAnswerIndex: 2,
  },
  {
    id: 247,
    question: "¿Qué ciencia estudia los astros?",
    options: ["Astrología", "Astronomía", "Geología", "Biología"],
    correctAnswerIndex: 1,
  },
  {
    id: 248,
    question: "¿Qué órgano permite oír?",
    options: ["Nariz", "Ojo", "Oído", "Lengua"],
    correctAnswerIndex: 2,
  },
  {
    id: 249,
    question: "¿Qué planeta tiene más lunas conocidas?",
    options: ["Saturno", "Júpiter", "Urano", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 250,
    question: "¿Qué estado de la materia tiene forma definida?",
    options: ["Líquido", "Gas", "Plasma", "Sólido"],
    correctAnswerIndex: 3,
  },

  {
    id: 251,
    question: "¿Qué órgano transporta la sangre?",
    options: ["Venas", "Pulmones", "Riñones", "Hígado"],
    correctAnswerIndex: 0,
  },
  {
    id: 252,
    question: "¿Qué tipo de animal es el murciélago?",
    options: ["Ave", "Reptil", "Mamífero", "Anfibio"],
    correctAnswerIndex: 2,
  },
  {
    id: 253,
    question: "¿Qué planeta es el más caliente?",
    options: ["Mercurio", "Venus", "Marte", "Júpiter"],
    correctAnswerIndex: 1,
  },
  {
    id: 254,
    question: "¿Qué órgano controla el cuerpo humano?",
    options: ["Pulmón", "Cerebro", "Riñón", "Estómago"],
    correctAnswerIndex: 1,
  },
  {
    id: 255,
    question: "¿Qué energía se obtiene del Sol?",
    options: ["Solar", "Eólica", "Hidráulica", "Nuclear"],
    correctAnswerIndex: 0,
  },
  {
    id: 256,
    question: "¿Qué planeta tiene anillos además de Saturno?",
    options: ["Júpiter", "Urano", "Neptuno", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 257,
    question: "¿Qué órgano produce la orina?",
    options: ["Hígado", "Pulmones", "Riñones", "Páncreas"],
    correctAnswerIndex: 2,
  },
  {
    id: 258,
    question: "¿Qué animal respira por branquias?",
    options: ["Perro", "Ballena", "Pez", "Delfín"],
    correctAnswerIndex: 2,
  },
  {
    id: 259,
    question: "¿Qué planeta es el más pequeño?",
    options: ["Mercurio", "Marte", "Venus", "Plutón"],
    correctAnswerIndex: 0,
  },
  {
    id: 260,
    question: "¿Qué órgano permite el gusto?",
    options: ["Nariz", "Lengua", "Oído", "Ojo"],
    correctAnswerIndex: 1,
  },

  {
    id: 261,
    question: "¿Qué tipo de energía usa una central nuclear?",
    options: ["Térmica", "Nuclear", "Solar", "Eólica"],
    correctAnswerIndex: 1,
  },
  {
    id: 262,
    question: "¿Qué planeta tiene mayor gravedad?",
    options: ["Tierra", "Saturno", "Júpiter", "Marte"],
    correctAnswerIndex: 2,
  },
  {
    id: 263,
    question: "¿Qué órgano protege los pulmones?",
    options: ["Cráneo", "Costillas", "Columna", "Piel"],
    correctAnswerIndex: 1,
  },
  {
    id: 264,
    question: "¿Qué tipo de animal es la serpiente?",
    options: ["Anfibio", "Reptil", "Mamífero", "Ave"],
    correctAnswerIndex: 1,
  },
  {
    id: 265,
    question: "¿Qué ciencia estudia el clima?",
    options: ["Geología", "Meteorología", "Astronomía", "Biología"],
    correctAnswerIndex: 1,
  },
  {
    id: 266,
    question: "¿Qué órgano produce hormonas?",
    options: ["Pulmones", "Glándulas", "Riñones", "Estómago"],
    correctAnswerIndex: 1,
  },
  {
    id: 267,
    question: "¿Qué planeta tiene inclinación extrema?",
    options: ["Urano", "Venus", "Marte", "Mercurio"],
    correctAnswerIndex: 0,
  },
  {
    id: 268,
    question: "¿Qué órgano permite el olfato?",
    options: ["Oído", "Lengua", "Nariz", "Ojo"],
    correctAnswerIndex: 2,
  },
  {
    id: 269,
    question: "¿Qué tipo de energía se almacena en los alimentos?",
    options: ["Eléctrica", "Térmica", "Química", "Solar"],
    correctAnswerIndex: 2,
  },
  {
    id: 270,
    question: "¿Qué animal es vertebrado?",
    options: ["Medusa", "Lombriz", "Perro", "Pulpo"],
    correctAnswerIndex: 2,
  },

  {
    id: 271,
    question: "¿Qué planeta tiene mayor número de anillos?",
    options: ["Júpiter", "Saturno", "Urano", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 272,
    question: "¿Qué órgano regula la temperatura corporal?",
    options: ["Corazón", "Pulmones", "Piel", "Riñones"],
    correctAnswerIndex: 2,
  },
  {
    id: 273,
    question: "¿Qué tipo de animal es el cocodrilo?",
    options: ["Anfibio", "Reptil", "Mamífero", "Ave"],
    correctAnswerIndex: 1,
  },
  {
    id: 274,
    question: "¿Qué ciencia estudia la materia?",
    options: ["Biología", "Química", "Astronomía", "Geografía"],
    correctAnswerIndex: 1,
  },
  {
    id: 275,
    question: "¿Qué planeta tiene el mayor número de lunas?",
    options: ["Saturno", "Júpiter", "Urano", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 276,
    question: "¿Qué órgano permite mover el cuerpo?",
    options: ["Pulmones", "Músculos", "Riñones", "Hígado"],
    correctAnswerIndex: 1,
  },
  {
    id: 277,
    question: "¿Qué animal tiene sangre fría?",
    options: ["Perro", "Gato", "Lagarto", "Caballo"],
    correctAnswerIndex: 2,
  },
  {
    id: 278,
    question: "¿Qué planeta es famoso por sus tormentas?",
    options: ["Venus", "Júpiter", "Marte", "Mercurio"],
    correctAnswerIndex: 1,
  },
  {
    id: 279,
    question: "¿Qué órgano produce glóbulos rojos?",
    options: ["Corazón", "Médula ósea", "Pulmones", "Hígado"],
    correctAnswerIndex: 1,
  },
  {
    id: 280,
    question: "¿Qué tipo de energía se transforma en movimiento?",
    options: ["Cinética", "Química", "Solar", "Nuclear"],
    correctAnswerIndex: 0,
  },

  {
    id: 281,
    question: "¿Qué planeta tiene el año más corto?",
    options: ["Mercurio", "Venus", "Tierra", "Marte"],
    correctAnswerIndex: 0,
  },
  {
    id: 282,
    question: "¿Qué órgano filtra toxinas?",
    options: ["Pulmones", "Riñones", "Hígado", "Estómago"],
    correctAnswerIndex: 2,
  },
  {
    id: 283,
    question: "¿Qué tipo de animal es la ballena?",
    options: ["Pez", "Mamífero", "Reptil", "Anfibio"],
    correctAnswerIndex: 1,
  },
  {
    id: 284,
    question: "¿Qué ciencia estudia la electricidad?",
    options: ["Biología", "Física", "Química", "Geología"],
    correctAnswerIndex: 1,
  },
  {
    id: 285,
    question: "¿Qué planeta tiene atmósfera más densa?",
    options: ["Venus", "Marte", "Tierra", "Mercurio"],
    correctAnswerIndex: 0,
  },
  {
    id: 286,
    question: "¿Qué órgano produce la digestión?",
    options: ["Pulmones", "Estómago", "Riñones", "Cerebro"],
    correctAnswerIndex: 1,
  },
  {
    id: 287,
    question: "¿Qué animal puede vivir en agua y tierra?",
    options: ["Pez", "Anfibio", "Ave", "Reptil"],
    correctAnswerIndex: 1,
  },
  {
    id: 288,
    question: "¿Qué planeta tiene el eje más inclinado?",
    options: ["Urano", "Venus", "Marte", "Júpiter"],
    correctAnswerIndex: 0,
  },
  {
    id: 289,
    question: "¿Qué órgano permite pensar?",
    options: ["Pulmón", "Cerebro", "Riñón", "Hígado"],
    correctAnswerIndex: 1,
  },
  {
    id: 290,
    question: "¿Qué energía se libera en una explosión?",
    options: ["Solar", "Química", "Eólica", "Hidráulica"],
    correctAnswerIndex: 1,
  },

  {
    id: 291,
    question: "¿Qué planeta tiene mayor presión atmosférica?",
    options: ["Tierra", "Venus", "Marte", "Mercurio"],
    correctAnswerIndex: 1,
  },
  {
    id: 292,
    question: "¿Qué órgano permite escuchar sonidos?",
    options: ["Nariz", "Ojo", "Oído", "Lengua"],
    correctAnswerIndex: 2,
  },
  {
    id: 293,
    question: "¿Qué animal es ovíparo?",
    options: ["Perro", "Gato", "Gallina", "Vaca"],
    correctAnswerIndex: 2,
  },
  {
    id: 294,
    question: "¿Qué ciencia estudia el cuerpo humano?",
    options: ["Anatomía", "Astronomía", "Geología", "Botánica"],
    correctAnswerIndex: 0,
  },
  {
    id: 295,
    question: "¿Qué planeta tiene volcanes activos?",
    options: ["Marte", "Venus", "Tierra", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 296,
    question: "¿Qué órgano controla las hormonas?",
    options: ["Sistema nervioso", "Sistema endocrino", "Sistema digestivo", "Sistema óseo"],
    correctAnswerIndex: 1,
  },
  {
    id: 297,
    question: "¿Qué animal es carnívoro?",
    options: ["Vaca", "Conejo", "León", "Caballo"],
    correctAnswerIndex: 2,
  },
  {
    id: 298,
    question: "¿Qué planeta tiene el día más largo que el año?",
    options: ["Mercurio", "Venus", "Marte", "Júpiter"],
    correctAnswerIndex: 1,
  },
  {
    id: 299,
    question: "¿Qué órgano produce la sangre?",
    options: ["Corazón", "Médula ósea", "Pulmón", "Hígado"],
    correctAnswerIndex: 1,
  },
  {
    id: 300,
    question: "¿Qué tipo de energía proviene del calor interno de la Tierra?",
    options: ["Solar", "Geotérmica", "Eólica", "Nuclear"],
    correctAnswerIndex: 1,
  },
];
