// IDs del 501 al 600
export const QUESTION_CURIOCIDAD = [
  {
    id: 501,
    question: "¿Cuál es el animal con el corazón más grande?",
    options: ["Elefante", "Ballena azul", "Jirafa", "Tiburón"],
    correctAnswerIndex: 1,
  },
  {
    id: 502,
    question: "¿Cuántos huesos tiene el cuerpo humano adulto?",
    options: ["198", "206", "212", "220"],
    correctAnswerIndex: 1,
  },
  {
    id: 503,
    question: "¿Cuál es el país más grande del mundo?",
    options: ["Canadá", "China", "Estados Unidos", "Rusia"],
    correctAnswerIndex: 3,
  },
  {
    id: 504,
    question: "¿Qué órgano del cuerpo nunca descansa?",
    options: ["Pulmón", "Corazón", "Cerebro", "Riñón"],
    correctAnswerIndex: 1,
  },
  {
    id: 505,
    question: "¿Cuál es el metal más abundante en la corteza terrestre?",
    options: ["Hierro", "Aluminio", "Cobre", "Oro"],
    correctAnswerIndex: 1,
  },
  {
    id: 506,
    question: "¿Cuántos litros de sangre tiene en promedio un adulto?",
    options: ["3 litros", "5 litros", "7 litros", "10 litros"],
    correctAnswerIndex: 1,
  },
  {
    id: 507,
    question: "¿Qué planeta gira más rápido sobre su eje?",
    options: ["Marte", "Júpiter", "Saturno", "Tierra"],
    correctAnswerIndex: 1,
  },
  {
    id: 508,
    question: "¿Cuál es el animal terrestre más grande?",
    options: ["Rinoceronte", "Elefante africano", "Hipopótamo", "Jirafa"],
    correctAnswerIndex: 1,
  },
  {
    id: 509,
    question: "¿Cuál es el idioma con más hablantes nativos?",
    options: ["Inglés", "Español", "Mandarín", "Hindi"],
    correctAnswerIndex: 2,
  },
  {
    id: 510,
    question: "¿Qué parte del cuerpo humano se renueva más rápido?",
    options: ["Piel", "Uñas", "Cabello", "Lengua"],
    correctAnswerIndex: 3,
  },

  {
    id: 511,
    question: "¿Cuál es el desierto más grande del mundo?",
    options: ["Sahara", "Gobi", "Antártida", "Kalahari"],
    correctAnswerIndex: 2,
  },
  {
    id: 512,
    question: "¿Cuántos dientes tiene un adulto normalmente?",
    options: ["28", "30", "32", "36"],
    correctAnswerIndex: 2,
  },
  {
    id: 513,
    question: "¿Qué animal duerme de pie?",
    options: ["Vaca", "Elefante", "Caballo", "Jirafa"],
    correctAnswerIndex: 2,
  },
  {
    id: 514,
    question: "¿Cuál es el océano más grande?",
    options: ["Atlántico", "Índico", "Ártico", "Pacífico"],
    correctAnswerIndex: 3,
  },
  {
    id: 515,
    question: "¿Qué órgano consume más energía del cuerpo?",
    options: ["Corazón", "Pulmones", "Cerebro", "Hígado"],
    correctAnswerIndex: 2,
  },
  {
    id: 516,
    question: "¿Qué animal puede vivir sin cabeza varios días?",
    options: ["Araña", "Hormiga", "Cucaracha", "Escorpión"],
    correctAnswerIndex: 2,
  },
  {
    id: 517,
    question: "¿Cuál es el hueso más pequeño del cuerpo?",
    options: ["Martillo", "Yunque", "Estribo", "Falange"],
    correctAnswerIndex: 2,
  },
  {
    id: 518,
    question: "¿Qué planeta tiene más lunas conocidas?",
    options: ["Júpiter", "Saturno", "Urano", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 519,
    question: "¿Cuánto dura un parpadeo?",
    options: ["0.1 segundos", "0.3 segundos", "1 segundo", "2 segundos"],
    correctAnswerIndex: 1,
  },
  {
    id: 520,
    question: "¿Qué animal tiene la mordida más fuerte?",
    options: ["León", "Tiburón blanco", "Cocodrilo", "Hiena"],
    correctAnswerIndex: 2,
  },

  {
    id: 521,
    question: "¿Qué porcentaje del cuerpo humano es agua?",
    options: ["50%", "60%", "70%", "80%"],
    correctAnswerIndex: 1,
  },
  {
    id: 522,
    question: "¿Cuál es el objeto natural más duro?",
    options: ["Hierro", "Diamante", "Granito", "Cuarzo"],
    correctAnswerIndex: 1,
  },
  {
    id: 523,
    question: "¿Cuántos músculos tiene el cuerpo humano?",
    options: ["Más de 300", "Más de 400", "Más de 600", "Más de 800"],
    correctAnswerIndex: 2,
  },
  {
    id: 524,
    question: "¿Qué animal puede regenerar extremidades?",
    options: ["Lagarto", "Pulpo", "Estrella de mar", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 525,
    question: "¿Cuál es el país con más islas?",
    options: ["Indonesia", "Filipinas", "Suecia", "Japón"],
    correctAnswerIndex: 2,
  },
  {
    id: 526,
    question: "¿Qué órgano humano puede regenerarse?",
    options: ["Corazón", "Pulmón", "Hígado", "Cerebro"],
    correctAnswerIndex: 2,
  },
  {
    id: 527,
    question: "¿Qué animal tiene tres corazones?",
    options: ["Pulpo", "Ballena", "Tiburón", "Delfín"],
    correctAnswerIndex: 0,
  },
  {
    id: 528,
    question: "¿Cuántos cromosomas tiene el ser humano?",
    options: ["42", "44", "46", "48"],
    correctAnswerIndex: 2,
  },
  {
    id: 529,
    question: "¿Qué animal nunca deja de crecer?",
    options: ["Serpiente", "Cangrejo", "Tiburón", "Cocodrilo"],
    correctAnswerIndex: 2,
  },
  {
    id: 530,
    question: "¿Qué sentido se desarrolla primero en el ser humano?",
    options: ["Vista", "Oído", "Olfato", "Tacto"],
    correctAnswerIndex: 2,
  },

  {
    id: 531,
    question: "¿Cuál es el lago más profundo del mundo?",
    options: ["Titicaca", "Victoria", "Baikal", "Superior"],
    correctAnswerIndex: 2,
  },
  {
    id: 532,
    question: "¿Cuántos sabores básicos existen?",
    options: ["3", "4", "5", "6"],
    correctAnswerIndex: 2,
  },
  {
    id: 533,
    question: "¿Qué animal puede imitar sonidos humanos?",
    options: ["Loro", "Cuervo", "Delfín", "Mono"],
    correctAnswerIndex: 0,
  },
  {
    id: 534,
    question: "¿Cuál es el volcán más alto del mundo?",
    options: ["Etna", "Kilimanjaro", "Ojos del Salado", "Vesubio"],
    correctAnswerIndex: 2,
  },
  {
    id: 535,
    question: "¿Qué parte del cuerpo produce adrenalina?",
    options: ["Riñones", "Glándulas suprarrenales", "Hígado", "Páncreas"],
    correctAnswerIndex: 1,
  },
  {
    id: 536,
    question: "¿Qué animal puede ver en casi total oscuridad?",
    options: ["Perro", "Gato", "Búho", "Murciélago"],
    correctAnswerIndex: 1,
  },
  {
    id: 537,
    question: "¿Qué planeta tiene el día más largo?",
    options: ["Mercurio", "Venus", "Marte", "Júpiter"],
    correctAnswerIndex: 1,
  },
  {
    id: 538,
    question: "¿Cuál es el río más largo del mundo?",
    options: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"],
    correctAnswerIndex: 0,
  },
  {
    id: 539,
    question: "¿Qué animal tiene la lengua más larga en proporción?",
    options: ["Jirafa", "Camaleón", "Oso hormiguero", "Serpiente"],
    correctAnswerIndex: 1,
  },
  {
    id: 540,
    question: "¿Qué parte del cuerpo humano no recibe sangre?",
    options: ["Córnea", "Uñas", "Cabello", "Todas"],
    correctAnswerIndex: 3,
  },

  {
    id: 541,
    question: "¿Qué animal puede vivir más años?",
    options: ["Elefante", "Tortuga", "Ballena", "Loro"],
    correctAnswerIndex: 1,
  },
  {
    id: 542,
    question: "¿Cuántas veces late el corazón al día?",
    options: ["50 mil", "80 mil", "100 mil", "120 mil"],
    correctAnswerIndex: 2,
  },
  {
    id: 543,
    question: "¿Qué animal puede dormir con un ojo abierto?",
    options: ["Delfín", "Pato", "Tiburón", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 544,
    question: "¿Qué país consume más chocolate per cápita?",
    options: ["Alemania", "Suiza", "Bélgica", "Francia"],
    correctAnswerIndex: 1,
  },
  {
    id: 545,
    question: "¿Qué órgano humano es el más grande?",
    options: ["Hígado", "Pulmón", "Piel", "Intestino"],
    correctAnswerIndex: 2,
  },
  {
    id: 546,
    question: "¿Cuántos planetas hay en el sistema solar?",
    options: ["7", "8", "9", "10"],
    correctAnswerIndex: 1,
  },
  {
    id: 547,
    question: "¿Qué animal no puede saltar?",
    options: ["Elefante", "Rinoceronte", "Hipopótamo", "Todos"],
    correctAnswerIndex: 0,
  },
  {
    id: 548,
    question: "¿Cuál es el país más poblado?",
    options: ["India", "China", "Estados Unidos", "Indonesia"],
    correctAnswerIndex: 0,
  },
  {
    id: 549,
    question: "¿Qué gas hace flotar los globos?",
    options: ["Oxígeno", "Hidrógeno", "Helio", "Nitrógeno"],
    correctAnswerIndex: 2,
  },
  {
    id: 550,
    question: "¿Qué animal tiene huellas únicas como los humanos?",
    options: ["Perro", "Gato", "Koala", "Oso"],
    correctAnswerIndex: 2,
  },

  {
    id: 551,
    question: "¿Cuál es el órgano más pesado del cuerpo?",
    options: ["Cerebro", "Pulmón", "Hígado", "Piel"],
    correctAnswerIndex: 3,
  },
  {
    id: 552,
    question: "¿Qué animal puede correr más rápido?",
    options: ["León", "Guepardo", "Antílope", "Avestruz"],
    correctAnswerIndex: 1,
  },
  {
    id: 553,
    question: "¿Qué parte del cuerpo tiene más terminaciones nerviosas?",
    options: ["Lengua", "Dedos", "Labios", "Cara"],
    correctAnswerIndex: 2,
  },
  {
    id: 554,
    question: "¿Qué planeta tiene más volcanes?",
    options: ["Tierra", "Venus", "Marte", "Júpiter"],
    correctAnswerIndex: 1,
  },
  {
    id: 555,
    question: "¿Qué animal puede vivir sin oxígeno varios días?",
    options: ["Tortuga", "Rana", "Cucaracha", "Pez"],
    correctAnswerIndex: 2,
  },
  {
    id: 556,
    question: "¿Cuál es el hueso más fuerte?",
    options: ["Fémur", "Tibia", "Cráneo", "Húmero"],
    correctAnswerIndex: 0,
  },
  {
    id: 557,
    question: "¿Qué animal tiene la memoria más larga?",
    options: ["Perro", "Elefante", "Delfín", "Mono"],
    correctAnswerIndex: 1,
  },
  {
    id: 558,
    question: "¿Qué sentido humano es más fuerte al nacer?",
    options: ["Vista", "Oído", "Olfato", "Gusto"],
    correctAnswerIndex: 2,
  },
  {
    id: 559,
    question: "¿Qué animal puede detectar terremotos?",
    options: ["Perro", "Gato", "Elefante", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 560,
    question: "¿Cuál es el lugar más frío de la Tierra?",
    options: ["Groenlandia", "Antártida", "Siberia", "Alaska"],
    correctAnswerIndex: 1,
  },

  {
    id: 561,
    question: "¿Qué animal puede cambiar de color?",
    options: ["Pulpo", "Camaleón", "Calamar", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 562,
    question: "¿Cuántos litros de aire respiramos al día?",
    options: ["5.000", "10.000", "15.000", "20.000"],
    correctAnswerIndex: 3,
  },
  {
    id: 563,
    question: "¿Qué animal tiene el embarazo más largo?",
    options: ["Ballena", "Elefante", "Rinoceronte", "Jirafa"],
    correctAnswerIndex: 1,
  },
  {
    id: 564,
    question: "¿Qué parte del cerebro controla las emociones?",
    options: ["Cerebelo", "Lóbulo frontal", "Sistema límbico", "Hipotálamo"],
    correctAnswerIndex: 2,
  },
  {
    id: 565,
    question: "¿Qué animal puede vivir más tiempo sin agua?",
    options: ["Camello", "Rata canguro", "Serpiente", "Escorpión"],
    correctAnswerIndex: 1,
  },
  {
    id: 566,
    question: "¿Qué órgano humano se regenera cada 10 días?",
    options: ["Piel", "Hígado", "Lengua", "Estómago"],
    correctAnswerIndex: 2,
  },
  {
    id: 567,
    question: "¿Cuál es la montaña más alta del mundo?",
    options: ["K2", "Everest", "Aconcagua", "Makalu"],
    correctAnswerIndex: 1,
  },
  {
    id: 568,
    question: "¿Qué animal puede respirar por la piel?",
    options: ["Serpiente", "Rana", "Lagarto", "Pez"],
    correctAnswerIndex: 1,
  },
  {
    id: 569,
    question: "¿Qué órgano humano sigue creciendo toda la vida?",
    options: ["Orejas", "Nariz", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 570,
    question: "¿Qué planeta tiene el mayor tamaño?",
    options: ["Saturno", "Neptuno", "Júpiter", "Urano"],
    correctAnswerIndex: 2,
  },

  {
    id: 571,
    question: "¿Qué animal tiene la sangre azul?",
    options: ["Pulpo", "Cangrejo herradura", "Ambos", "Ninguno"],
    correctAnswerIndex: 2,
  },
  {
    id: 572,
    question: "¿Cuántos segundos dura un recuerdo a corto plazo?",
    options: ["10", "20", "30", "60"],
    correctAnswerIndex: 2,
  },
  {
    id: 573,
    question: "¿Qué animal puede detectar campos magnéticos?",
    options: ["Tortuga", "Ave migratoria", "Tiburón", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 574,
    question: "¿Qué parte del cuerpo humano tiene más bacterias?",
    options: ["Manos", "Boca", "Intestino", "Pies"],
    correctAnswerIndex: 2,
  },
  {
    id: 575,
    question: "¿Qué animal tiene los ojos más grandes?",
    options: ["Calamar gigante", "Ballena", "Elefante", "Pulpo"],
    correctAnswerIndex: 0,
  },
  {
    id: 576,
    question: "¿Qué planeta tiene más gravedad?",
    options: ["Tierra", "Saturno", "Júpiter", "Neptuno"],
    correctAnswerIndex: 2,
  },
  {
    id: 577,
    question: "¿Qué animal puede vivir sin cerebro?",
    options: ["Medusa", "Estrella de mar", "Esponja", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 578,
    question: "¿Qué órgano humano es el primero en formarse?",
    options: ["Cerebro", "Corazón", "Pulmones", "Hígado"],
    correctAnswerIndex: 1,
  },
  {
    id: 579,
    question: "¿Qué animal puede ver en 360 grados?",
    options: ["Camaleón", "Mosca", "Caballo", "Ave"],
    correctAnswerIndex: 0,
  },
  {
    id: 580,
    question: "¿Cuál es el material más resistente conocido?",
    options: ["Acero", "Diamante", "Grafeno", "Titanio"],
    correctAnswerIndex: 2,
  },

  {
    id: 581,
    question: "¿Qué animal puede oír frecuencias ultrasónicas?",
    options: ["Perro", "Murciélago", "Delfín", "Todos"],
    correctAnswerIndex: 3,
  },
  {
    id: 582,
    question: "¿Qué parte del cuerpo humano tiene menos riego sanguíneo?",
    options: ["Uñas", "Cabello", "Córnea", "Piel"],
    correctAnswerIndex: 2,
  },
  {
    id: 583,
    question: "¿Qué animal puede regenerar el corazón?",
    options: ["Rana", "Ajolote", "Lagarto", "Pez"],
    correctAnswerIndex: 1,
  },
  {
    id: 584,
    question: "¿Cuántos sentidos tiene el ser humano según la ciencia?",
    options: ["5", "7", "10", "Más de 10"],
    correctAnswerIndex: 3,
  },
  {
    id: 585,
    question: "¿Qué animal puede sobrevivir en el espacio?",
    options: ["Cucaracha", "Tardígrado", "Hormiga", "Escarabajo"],
    correctAnswerIndex: 1,
  },
  {
    id: 586,
    question: "¿Qué órgano humano consume más oxígeno?",
    options: ["Corazón", "Pulmones", "Cerebro", "Riñones"],
    correctAnswerIndex: 2,
  },
  {
    id: 587,
    question: "¿Qué animal tiene el cerebro más grande?",
    options: ["Elefante", "Ballena azul", "Humano", "Delfín"],
    correctAnswerIndex: 1,
  },
  {
    id: 588,
    question: "¿Qué planeta tiene el mayor número de tormentas?",
    options: ["Marte", "Venus", "Júpiter", "Neptuno"],
    correctAnswerIndex: 2,
  },
  {
    id: 589,
    question: "¿Qué parte del cuerpo humano se cura más rápido?",
    options: ["Huesos", "Piel", "Músculos", "Nervios"],
    correctAnswerIndex: 1,
  },
  {
    id: 590,
    question: "¿Qué animal puede vivir más de 400 años?",
    options: ["Tortuga", "Almeja", "Ballena", "Coral"],
    correctAnswerIndex: 1,
  },

  {
    id: 591,
    question: "¿Qué órgano humano produce dopamina?",
    options: ["Cerebro", "Hígado", "Páncreas", "Riñones"],
    correctAnswerIndex: 0,
  },
  {
    id: 592,
    question: "¿Qué animal puede recordar rutas durante décadas?",
    options: ["Perro", "Elefante", "Paloma", "Mono"],
    correctAnswerIndex: 1,
  },
  {
    id: 593,
    question: "¿Qué planeta tiene la rotación más lenta?",
    options: ["Mercurio", "Venus", "Marte", "Neptuno"],
    correctAnswerIndex: 1,
  },
  {
    id: 594,
    question: "¿Qué animal puede ver luz ultravioleta?",
    options: ["Gato", "Perro", "Abeja", "Humano"],
    correctAnswerIndex: 2,
  },
  {
    id: 595,
    question: "¿Qué órgano humano se auto-limpia?",
    options: ["Pulmones", "Estómago", "Hígado", "Oído"],
    correctAnswerIndex: 1,
  },
  {
    id: 596,
    question: "¿Qué animal tiene el metabolismo más rápido?",
    options: ["Ratón", "Colibrí", "Murciélago", "Ardilla"],
    correctAnswerIndex: 1,
  },
  {
    id: 597,
    question: "¿Qué planeta tiene la atmósfera más espesa?",
    options: ["Venus", "Tierra", "Júpiter", "Titán"],
    correctAnswerIndex: 0,
  },
  {
    id: 598,
    question: "¿Qué animal puede oír a kilómetros?",
    options: ["Lobo", "Elefante", "Murciélago", "Perro"],
    correctAnswerIndex: 1,
  },
  {
    id: 599,
    question: "¿Qué órgano humano no se regenera?",
    options: ["Hígado", "Piel", "Cerebro", "Intestino"],
    correctAnswerIndex: 2,
  },
  {
    id: 600,
    question: "¿Qué animal puede vivir en condiciones extremas de temperatura?",
    options: ["Camello", "Oso polar", "Tardígrado", "Escorpión"],
    correctAnswerIndex: 2,
  },
];
